import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {interestDatabase} from '@/lib/interest-db';
import {readLabBody} from '@/lib/lab-http';
import {mayEditFramework,sameOriginMutation,proposeFrameworkChange,type FrameworkProposal} from '@/lib/framework-proposals';
import {reserveAiCall} from '@/lib/ai-research-transport';
import {TemporalInputError} from '@/lib/engine/temporal-router';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
type Row={id:string;created_at:string;updated_at:string;status:string;prompt:string;body_json:string|null;error:string|null};
const unpack=(r:Row)=>({id:r.id,createdAt:r.created_at,updatedAt:r.updated_at,status:r.status,prompt:r.prompt,proposal:r.body_json?JSON.parse(r.body_json):null,error:r.error});
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const isPublic=new URL(request.url).searchParams.get('public')==='1';if(!isPublic){const user=await getChatGPTUser();if(!mayEditFramework(user?.userId,(env as {OBSERVATORY_EDITOR_IDS?:string}).OBSERVATORY_EDITOR_IDS))return json({error:'Editor access required.'},403);}const rows=await interestDatabase().prepare(`SELECT id,created_at,updated_at,status,prompt,body_json,error FROM framework_proposals ${isPublic?"WHERE status IN ('candidate','retracted')":''} ORDER BY created_at DESC LIMIT 40`).all<Row>();return json({records:rows.results.map(unpack)});}catch{return json({error:'The proposal ledger is unavailable.'},503);}}
export async function POST(request:Request){const user=await getChatGPTUser(),e=env as {OBSERVATORY_EDITOR_IDS?:string;OPENAI_API_KEY?:string;OBSERVATORY_AI_MODEL?:string;OBSERVATORY_AI_DAILY_CALL_LIMIT?:string};if(!mayEditFramework(user?.userId,e.OBSERVATORY_EDITOR_IDS))return json({error:'Editor access required.'},403);if(!sameOriginMutation(request))return json({error:'Use the Observatory workshop to submit a change.'},403);let reservedId:string|undefined;try{const body=await readLabBody(request,12000) as Record<string,unknown>;if(!body||typeof body!=='object'||Array.isArray(body))return json({error:'Invalid request.'},400);const db=interestDatabase(),now=new Date().toISOString();
 if(body.action==='propose'){if(Object.keys(body).some(k=>!['action','id','prompt'].includes(k))||typeof body.id!=='string'||!/^[a-f0-9-]{36}$/.test(body.id)||typeof body.prompt!=='string'||!body.prompt.trim()||body.prompt.length>2000)return json({error:'A request ID and bounded research instruction are required.'},400);const existing=await db.prepare('SELECT id,created_at,updated_at,status,prompt,body_json,error FROM framework_proposals WHERE id=?').bind(body.id).first<Row>();if(existing){if(existing.prompt!==body.prompt)return json({error:'That request ID belongs to a different instruction.'},409);return json({record:unpack(existing)},existing.status==='generating'?202:200);}const inserted=await db.prepare("INSERT INTO framework_proposals(id,owner_id,created_at,updated_at,status,prompt) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING RETURNING id").bind(body.id,user!.userId,now,now,'generating',body.prompt).first();if(!inserted)return json({error:'That research instruction is already running.'},409);reservedId=body.id;const proposal=await proposeFrameworkChange(body.prompt,{apiKey:e.OPENAI_API_KEY,model:e.OBSERVATORY_AI_MODEL,dailyCallLimit:e.OBSERVATORY_AI_DAILY_CALL_LIMIT},()=>reserveAiCall(db,Number(e.OBSERVATORY_AI_DAILY_CALL_LIMIT)));await db.batch([db.prepare("UPDATE framework_proposals SET status='draft',body_json=?,updated_at=? WHERE id=? AND status='generating'").bind(JSON.stringify(proposal),new Date().toISOString(),body.id),db.prepare('INSERT INTO framework_events(id,proposal_id,actor_id,created_at,action,receipt) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),body.id,user!.userId,now,'draft_created',proposal.receiptSha256)]);return json({record:{id:body.id,createdAt:now,updatedAt:now,status:'draft',prompt:body.prompt,proposal,error:null}});}
 if(!['publish_candidate','retract'].includes(String(body.action))||typeof body.id!=='string'||Object.keys(body).some(k=>!['action','id'].includes(k)))return json({error:'Unknown framework operation.'},400);const row=await db.prepare('SELECT id,created_at,updated_at,status,prompt,body_json,error FROM framework_proposals WHERE id=?').bind(body.id).first<Row>();const before=body.action==='publish_candidate'?'draft':'candidate',after=body.action==='publish_candidate'?'candidate':'retracted';if(!row||row.status!==before||!row.body_json)return json({error:'The proposal changed. Refresh before continuing.'},409);const proposal=JSON.parse(row.body_json) as FrameworkProposal;if(proposal.classification!=='candidate'||proposal.review.state!=='needs_domain_review')return json({error:'Only an explicitly reviewed-as-pending candidate may be published.'},400);const changed=await db.batch([db.prepare('UPDATE framework_proposals SET status=?,updated_at=? WHERE id=? AND status=?').bind(after,now,body.id,before),db.prepare('INSERT INTO framework_events(id,proposal_id,actor_id,created_at,action,receipt) SELECT ?,?,?,?,?,? WHERE changes()>0').bind(crypto.randomUUID(),body.id,user!.userId,now,after,proposal.receiptSha256)]);if(changed[0].meta.changes!==1)return json({error:'The proposal changed. Refresh before continuing.'},409);return json({record:unpack({...row,status:after,updated_at:now})});
 }catch(error){const message=error instanceof TemporalInputError?error.message:'The research instruction could not complete. No candidate was published.';if(reservedId)await interestDatabase().prepare("UPDATE framework_proposals SET status='failed',error=?,updated_at=? WHERE id=? AND status='generating'").bind(message,new Date().toISOString(),reservedId).run().catch(()=>{});return json({error:message},503);}}
