/** These are editable premises, not findings generated by the reasoning engine. */
export const REASONING_EXAMPLES = [
  {
    name: 'Follow an object',
    description: 'A small English grammar plus one explicit rule. Change the objects or location and rerun.',
    prompt: `The ball is inside the box.
The box is at the shelf.
Rule: ?object | inside | ?container & ?container | at | ?place -> ?object | at | ?place
Where is the ball?`,
  },
  {
    name: 'Find missing information',
    description: 'The same rule is given, but the location is missing. Supply it in your next prompt.',
    prompt: `The parcel is inside the van.
Rule: ?object | inside | ?container & ?container | at | ?place -> ?object | at | ?place
Where is the parcel?`,
  },
  {
    name: 'Investigate our AI design',
    description: 'An authored engineering checklist, encoded as editable rules. Meeting this checklist would not prove general intelligence or that this is the cheapest architecture.',
    prompt: `Fact: observatory | has | session fact memory
Fact: observatory | has | explicit question parser
Fact: observatory | has | finite rule executor
Fact: observatory | has | derivation records
Fact: observatory | has | numerical model tools
Rule: ?system | has | session fact memory & ?system | has | explicit question parser & ?system | has | finite rule executor -> ?system | can | answer supported questions
Rule: ?system | can | answer supported questions & ?system | has | grounded feedback & ?system | has | candidate rule generator -> ?system | can | propose learning changes
Rule: ?system | can | propose learning changes & ?system | has | held-out evaluation & ?system | has | revision and rollback -> ?system | can | test learning changes
Rule: ?system | can | test learning changes & ?system | has | persistent learned world model -> ?system | meets | proposed learning-system contract
Ask: observatory | meets | proposed learning-system contract`,
  },
] as const;
