import source from '../public/research-cases/chlamydomonas/source-provenance.json' with {type:'json'};
import {CHLAM_STATE_LEDGER,CASE_EXPERIMENTS} from './case-engine-contract.ts';
export const CHLAMYDOMONAS_CASE={
 schema:'observatory-research-case/1',id:'BIO-CHLAM-001',revision:1,slug:'chlamydomonas',title:'What does a cell need to remember?',owner:'biology',deviceId:'chlamydomonas-aquarium',href:'/cases/chlamydomonas',
 classification:'conditional-model-and-prediction-audit',admission:'model_result_only_no_new_law',
 question:'Which equal-light histories look the same at a checkpoint yet divide differently under an identical future, and does a hidden-state predictor outperform a simple timing baseline?',
 finding:'The preserved published-model case gives 1 versus 8 descendants at 48h under equal light exposure and essentially equal lineage volume. A new finite-history search compares identical checkpoint volume, generation and integrated light under a common future; numerical refinement and a simple elapsed-darkness baseline are required. A hidden-state numerical artifact is rejected. Adding area-growth history worsens the pooled Brier score of 3,679 frozen held-out predictions by 3.30%. Run the case to obtain fresh calculations; this record alone does not execute them.',
 provenance:{...source,dataHref:'/research-cases/chlamydomonas/HELD_OUT_PREDICTIONS.json',dataSha256:source.assets['HELD_OUT_PREDICTIONS.json'],sourceFiles:Object.entries(source.assets).map(([name,sha256])=>({href:'/research-cases/chlamydomonas/'+name,sha256}))},
 nouns:CHLAM_STATE_LEDGER.map(r=>({name:r.noun,definition:r.unit+'; '+r.bound})),verbs:CHLAM_STATE_LEDGER.map(r=>r.verb),
 stateLedger:CHLAM_STATE_LEDGER,
 execution:{kind:'browser-worker',worker:'/research-cases/runtime/chlamydomonas-worker.mjs',adapter:'/research-cases/runtime/chlamydomonas-runner.mjs',protocol:'/research-cases/runtime/case-core.mjs',caseVersion:'chlamydomonas-case-engine/1',operations:CASE_EXPERIMENTS,request:{experiment:'state | timing | artifact | empirical',hours:[48,96],slots:[6,8]},budget:'One browser worker; two-minute execution timeout, bounded schedules and original solver step cap; no provider calls.',sourceModel:'/research-cases/chlamydomonas/MODEL_CONTRACT.json',allParameters:'/research-cases/chlamydomonas/PARAMETER_LEDGER.json',receipt:'SHA-256 canonical JSON; change detection, not authentication or proof.'},
 limits:['A finite deterministic model search cannot prove universal or minimum predictive state. A successful predictor is not automatically a causal mechanism.','The timing effect follows a published model; no novelty or biological validation is claimed.','AV and AU are arbitrary model units, time is minutes, light is binary. Pixel area has no calibrated transformation to AV.','The 20-history search has an independent BDF check for its selected witness; the 70-history extension has no registered independent reference.','Held-out-history scores are descriptive on a small deterministic synthetic split. The empirical replay re-scores frozen predictions without fitting or obtaining new observations.','Nutrients, energy, redox, membrane voltage, radiation, quantum coherence and full organism lifecycle remain missing adapters.'],
 corrections:[{revision:'source-recovery',status:'preserved',detail:'All 46 manifest-listed source files were verified unchanged. The source sandbox’s hidden-state lead and negative empirical result remain visible; neither was promoted into a discovery.'}],
 connections:[
  {room:'biology',device:'chlamydomonas-aquarium',role:'Model and observations',status:'case engine available',question:'Which measured state improves division prediction beyond size and recent light history?',requires:['Calibrated size and regulator measurements','Independent experiments','Predeclared observation time and horizon']},
  {room:'mathematics',device:'temporal-grammar',role:'Temporal grammar and growth identity',status:'conditional model link',question:'Can equal integrated forcing be insufficient for a future event when histories differ?',requires:['Same checkpoint observations','Identical future forcing','Declared state and event law']},
  {room:'engineering',device:'controller-comparison',role:'State and observation sufficiency',status:'finite search; no universal minimum state',question:'Does an added state variable outperform a simpler input-recency baseline?',requires:['Development-only feature selection','Held-out histories','Numerical robustness and competing baseline']},
  {room:'computing',device:'motion-learning',role:'Prediction and model selection',status:'candidate predictor only',question:'Which information earns predictive value on a frozen test partition?',requires:['No future labels as inputs','Equal prediction budget','No test-set feature selection']},
  {room:'chemistry',device:'chemistry-bench',role:'Resource and energy adapter',status:'unresolved',question:'Can measured resource chemistry be connected without relabelling light exposure as energy?',requires:['Chemical species and stoichiometry','Energy calibration','Matched compartment and time']},
  {room:'archive',device:'case-engine',role:'Shared evidence record',status:'versioned case protocol',question:'Which assumptions and results may other labs reuse?',requires:['Model and code identities','Unit-compatible ports','No scientific admission from a passing software check']},
 ],
 next:{title:'Test a measured regulator against size and light recency',state:'prospective protocol; no new empirical fitting',baseline:'Calibrated size + elapsed darkness versus the same predictor with a measured regulator proxy.',readiness:['Choose an assay that measures the intended regulator rather than a convenient label.','Freeze checkpoint, 24h outcome, censoring, formulas, fitting budget and experiment-level split.','Obtain independent lineages across enough independent experiments for the declared uncertainty procedure.'],success:'At least 5% lower held-out Brier score, experiment-cluster 95% interval for improvement entirely above zero, and calibration slope 0.8–1.2. These are proposed gates, not externally registered or executed.',failure:'Any evaluable performance miss rejects the advantage. Missing calibration or insufficient independent experiments is unresolved.',beforeFitting:'No retuning the already explored data into a confirmatory result.'},
} as const;
export const CHLAMYDOMONAS_BRIEF={id:'S-CHLAMYDOMONAS',branch:'biology',title:CHLAMYDOMONAS_CASE.title,evidence:'Published eight-state model; finite-history state search; rejected solver artifact; frozen real-data prediction replay. No new law admitted.',href:CHLAMYDOMONAS_CASE.href,finding:CHLAMYDOMONAS_CASE.finding+' The /cases/chlamydomonas worker runs locally with zero AI calls. The central guide reads this brief; it has not run the case. Energy and quantum connections remain unsupported.'};
