/** Public contributions only. Private proposed mechanisms are deliberately outside this registry. */
export type Contribution={id:string;title:string;class:string;finding:string;premises:string;unlock:string;limit:string;source:string;room:string;ancestry:string};
export const CONTRIBUTIONS:Contribution[]=[
 {id:'observatory',title:'The Observatory is the instrument',class:'Programme architecture · implemented in part',finding:'Turn observations, operations, proofs, counterexamples and experiments into a navigable, revisable research system. Rooms are interfaces to shared evidence, not separate stores of truth.',premises:'Stable identities, explicit dependencies, reproducible execution and an admission process that distinguishes evidence classes.',unlock:'A result in one room can constrain a question in another. A failed premise can identify the claims that need reassessment.',limit:'The full adaptive engine is a programme objective. The current site has reviewed fixed operations and proposal workflows; it does not autonomously certify new science.',source:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7427098',room:'/framework',ancestry:'Predictive state, sufficient statistics, formal methods and scientific provenance.'},
 {id:'composition',title:'One bounded range. Different lawful geometries.',class:'Conditional mathematics · manuscript',finding:'The composition mechanism selects the useful coordinate. A shared bounded output does not make independent action and dose equivalence the same operation.',premises:'The Aczél representation requires continuity, associativity, strict monotonicity and an identity on an appropriate interval. The pharmacology comparison additionally declares its mechanism and common Hill slope.',unlock:'Choose a discriminating experiment where competing composition laws disagree. Explore the exact n = 1 example below.',limit:'Hill, Bliss, Loewe and additive-generator theory are classical. The programme contribution is their operational synthesis and specified deductions; boundedness alone does not force Möbius geometry.',source:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7426978',room:'/labs/mathematics',ancestry:'Aczél representation; Hill saturation; Bliss independence; Loewe dose equivalence.'},
 {id:'current',title:'A neutral-looking distribution can hide a current',class:'Conditional identifiability result · manuscript',finding:'A stationary abundance distribution need not determine the probability current. Different dynamics can share the same occupancy statistics.',premises:'A declared stationary system, admissible transition dynamics and observations that distinguish occupancy from time-ordered transitions. The ecological formulation uses a persistent positive species core.',unlock:'Record ordered transitions and compare mechanisms that agree on the static distribution.',limit:'A time arrow alone does not establish niche interaction. Forcing, nonstationarity, observation effects and neutral currents must be compared.',source:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6963360',room:'/labs/biology',ancestry:'Aitchison composition geometry; stationary stochastic processes and probability currents.'},
 {id:'closure',title:'When may the past be forgotten?',class:'Conditional framework · current manuscripts',finding:'Two histories may share a retained state only relative to the future questions and actions that the state must support. Failure on a common continuation exposes an insufficient representation.',premises:'Specified observation channels, interventions, future tests and equality or tolerance criteria. Predictive sufficiency and safe action sufficiency are distinct.',unlock:'Retain a minimal useful state, and expand it when a reproducible failure reveals a missing distinction.',limit:'Order dependence by itself does not prove a hidden state. Finite successful tests do not establish universal closure.',source:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7425878',room:'/workbenches/learning',ancestry:'Sufficient statistics, predictive-state models, state abstraction and decision theory.'},
 {id:'geometry',title:'When composition determines geometry',class:'Conditional classification · legacy manuscript',finding:'The manuscript develops a flat-versus-Einstein classification from a specified package of bounded-composition axioms. Reassociation defects connect algebraic operations to geometric structure.',premises:'Smoothness, closure, identity, left inverses, the left-inverse property, orthogonal equivariance, an exact diameter law and an isometric-defect requirement. These are substantive extra conditions.',unlock:'Ask which observations distinguish associative flat composition from a non-associative branch, and identify the symmetry and regularity each inference needs.',limit:'This is a theorem claim under a declared axiom package, not a deduction from boundedness alone or a universal physical validation. The source is a legacy manuscript; dimensional refinements and public-version parity need review.',source:'https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6914800',room:'/labs/mathematics',ancestry:'Riemannian geometry, Einstein gyroaddition, rapidity and Thomas–Wigner rotations.'},
 {id:'paired-damage',title:'A cell-damage case that every room can inspect',class:'Exploratory real-data reanalysis · corrected record',finding:'A shared Biology dossier retains source data, corrected counts, exclusions and decision-horizon questions. Its replay is the common object other rooms reference.',premises:'The declared data, observation pipeline, lineage interpretation and analysis margins. Measured records and model-derived quantities retain different labels.',unlock:'Reuse the same audited case across Biology, temporal grammar, dynamics and observation theory.',limit:'The case does not establish a new biological force. Observational equivalence and unresolved measurement conventions constrain interpretation.',source:'/cases/paired-damage',room:'/labs/biology',ancestry:'Published cell-damage data; explicit observation and identifiability audits.'},
];
export const ENGINE_STAGES=[
 {id:'observe',title:'Observe',question:'What can the instrument distinguish?',href:'/labs/biology'},
 {id:'bound',title:'Bound',question:'What is limited, in which units, and why?',href:'/labs/mathematics'},
 {id:'compose',title:'Compose',question:'Which operations actually describe change?',href:'/question/papers'},
 {id:'retain',title:'Retain',question:'Which history does the next action need?',href:'/active-context'},
 {id:'challenge',title:'Challenge',question:'What experiment separates the alternatives?',href:'/workbenches/learning'},
 {id:'admit',title:'Admit & connect',question:'What follows, and what must be revised?',href:'/framework/work'},
];
export function compositionGap(a:number,b:number){if(!Number.isFinite(a)||!Number.isFinite(b)||a<=0||a>=1||b<=0||b>=1)throw new RangeError('Effects must be interior fractions.');const bliss=a+b-a*b,loewe=(a+b-2*a*b)/(1-a*b);return{bliss,loewe,gap:bliss-loewe};}
export function stationaryRing(forward:number){if(!Number.isFinite(forward)||forward<0||forward>0.9)throw new RangeError('Forward probability must be in [0, 0.9].');const back=0.9-forward;const transition=[[.1,forward,back],[back,.1,forward],[forward,back,.1]];return{transition,occupancy:[1/3,1/3,1/3],current:(forward-back)/3};}
