export type LabIdentity = { id:string; number:string; title:string; question:string; description:string; image:'precision'|'life'; accent:string; example?:string; kind:string; link?:{href:string;label:string} };
export const LAB_IDENTITIES:Record<string,LabIdentity> = {
  mathematics:{id:'mathematics',number:'01',title:'The Mathematics Room',question:'The same actions. A different answer?',description:'Compare exact operations, change their order, and inspect the assumptions that make a result true.',image:'precision',accent:'#d4b97b',example:'order',kind:'Exact mathematical models',link:{href:'/question/papers',label:'Open the paper challenges'}},
  biology:{id:'biology',number:'02',title:'The Living Systems Lab',question:'A signal recovers. What did it cost?',description:'Follow the resource ledger beneath a recovered signal. Separate a necessary ceiling from what a cell can actually achieve.',image:'life',accent:'#b1ce94',example:'resource',kind:'Declared resource models',link:{href:'/cell',label:'Explore recorded cell responses'}},
  quantum:{id:'quantum',number:'03',title:'The Quantum Room',question:'Which pathway changes the outcome?',description:'Compare singlet and triplet reaction yields under a declared reference protocol. Keep the preparation and the measurement in view.',image:'precision',accent:'#c7b5e2',example:'quantum',kind:'Dimensionless quantum reference',link:{href:'/#quantum',label:'Try the separate quantum beacon experiment'}},
  dynamics:{id:'dynamics',number:'04',title:'The Control Room',question:'What actually brings a system back?',description:'Give competing controllers the same disturbance. Compare the recovery, including where a conventional baseline wins.',image:'precision',accent:'#99cfc2',example:'control',kind:'Seeded control simulations',link:{href:'/#tao',label:'Take the live reactor controls'}},
  temporal:{id:'temporal',number:'05',title:'The Time & Sequence Room',question:'What changes when before becomes after?',description:'An operation needs a state, an order and a context. Begin with an exact sequence comparison, then inspect the inquiry grammar.',image:'precision',accent:'#dfb789',example:'order',kind:'Temporal grammar & ordered models',link:{href:'/agents',label:'Inspect the structured inquiry contract'}},
  encyclopedia:{id:'encyclopedia',number:'06',title:'The Reading Room',question:'What would make us change our minds?',description:'A finding belongs with its source, conditions and open questions. Run an example and follow its evidence into the library.',image:'life',accent:'#d7c697',example:'order',kind:'Source-pinned research records',link:{href:'/encyclopedia',label:'Open the research library'}},
  tao:{id:'tao',number:'07',title:'The Reactor Bench',question:'Can you bring it back into balance?',description:'Choose a controller, disturb the simulated reserve, and watch its recovery against the target.',image:'precision',accent:'#98cfc0',kind:'Interactive control simulation'},
  behaviour:{id:'behaviour',number:'08',title:'The Attention Bench',question:'When does a signal become a response?',description:'Compare response windows using your own timing. The experiment starts only after your consent.',image:'life',accent:'#e3bc83',kind:'24-trial local response experiment'},
  beacon:{id:'beacon',number:'09',title:'The Quantum Beacon',question:'Which measurement will tell you more?',description:'Choose a basis, measure fresh simulated copies, and narrow the possible hidden states.',image:'precision',accent:'#c8b5e6',kind:'Six-state quantum simulation'},
  human:{id:'human',number:'10',title:'The Human Condition Lab',question:'How does the world reach the body?',description:'Explore anatomical structures, pathways and history while keeping evidence and timescales visible.',image:'life',accent:'#b6d09d',kind:'Educational systems explorer'},
  cell:{id:'cell',number:'11',title:'The Cell Observatory',question:'Does the prediction survive another cell?',description:'Choose a context, inspect the prediction, then reveal the recorded response.',image:'life',accent:'#b7cca6',kind:'Recorded gene-response data'},
  recovery:{id:'recovery',number:'12',title:'The Recovery Archive',question:'Does the present tell the whole story?',description:'Inspect a recorded history before revealing its future. Compare what each description can predict.',image:'life',accent:'#dab685',kind:'Recorded recovery cases'},
  families:{id:'families',number:'13',title:'The Adaptation Field Station',question:'What do they learn to keep alive?',description:'Six synthetic learners share a world. Inspect the actual updates, trade-offs and limits of their learning.',image:'life',accent:'#c9c487',kind:'Live synthetic world'},
  context:{id:'context',number:'14',title:'The Context Archive',question:'Is yesterday’s evidence still usable?',description:'Replay a handoff and inspect which checks remain valid when the working context changes.',image:'precision',accent:'#d0bd91',kind:'Recorded verification replay'},
  atlas:{id:'atlas',number:'15',title:'The Programme Atlas',question:'How does one question connect to another?',description:'Follow the programme across scales and branches, with sources and unresolved tests attached.',image:'precision',accent:'#a4c9c4',kind:'Research map'},
  instrument:{id:'instrument',number:'16',title:'The Instrument Dock',question:'What did the instrument actually observe?',description:'Connect a local measurement adapter, inspect its source and clock, then preserve a session.',image:'precision',accent:'#acccb7',kind:'Local adapter interface'},
  expeditions:{id:'expeditions',number:'17',title:'The Field Expeditions',question:'What changed beyond this room?',description:'Follow Earth observations, memory replays and genome context through their existing instruments.',image:'life',accent:'#c7c58e',kind:'Data & model expeditions'},
  logbook:{id:'logbook',number:'18',title:'Your Experiment Logbook',question:'Leave a trail you can follow.',description:'Return to your local experiments, inspect their inputs, and export the record.',image:'precision',accent:'#d8c393',kind:'This browser’s experiment records'},
};
export const sceneFor = (lab:LabIdentity) => lab.image === 'life' ? '/images/life-workbench.webp' : '/images/precision-workbench.webp';
