/** Presentation can move; instrument identities, engines and evidence stay stable. */
export type Device={id:string;label:string;object:string;purpose:string;kind:string;href?:string;branch?:string;source:string;related:string[]};
export type Placement={device:string;x:number;y:number;w:number;h:number};
export type ScienceRoom={id:string;name:string;title:string;description:string;disciplines:string[];image:string;accent:string;station:string;construction?:boolean;devices:Placement[];mergedInto?:string};
const d=(id:string,label:string,object:string,purpose:string,kind:string,href:string|undefined,source:string,related:string[]=[],branch?:string):Device=>({id,label,object,purpose,kind,href,source,related,branch});
const p=(device:string,x:number,y:number,w=18,h=22):Placement=>({device,x,y,w,h});
export const DEVICES:Device[]=[
 d('ordered-model','Order & boundedness','Open notebook','Reverse two declared operations and inspect their exact results.','Conditional mathematics',undefined,'lib/engine/temporal-router.ts',['paper-challenges','temporal-grammar'],'mathematics'),
 d('paper-challenges','Paper challenges','Proof drawer','Test numerical challenges to the programme’s mathematical claims.','Executable model checks','/question/papers','components/observatory/PaperChallenges.tsx',['ordered-model']),
 d('temporal-grammar','Temporal grammar','Timing instrument','Make state, preparation, action order and observation explicit.','Declared inquiry model',undefined,'lib/engine/temporal-router.ts',['ordered-model','agent-interface'],'temporal'),
 d('quantum-reference','Reaction pathways','Optical bench','Compare singlet and triplet yields under the declared reference protocol.','Dimensionless simulation',undefined,'lib/engine/quantum-reference.ts',['quantum-beacon','schrodinger-cabinet'],'quantum'),
 d('quantum-beacon','Quantum beacon','Oscilloscope','Choose a basis and distinguish six simulated states.','Six-state simulation','/?embedded=1#quantum','components/observatory/QuantumLab.tsx',['quantum-reference']),
 d('schrodinger-cabinet','Schrödinger’s cabinet','Cat under glass','An interactive measurement thought experiment is planned. The cat is a room prop; no experiment runs here yet.','Under construction',undefined,'research/Observatory_Room_Architecture.md',['quantum-reference']),
 d('resource-ledger','Resource ledger','Surgery chart','Calculate a necessary biochemical ceiling from explicitly declared pools.','Conditional resource bound',undefined,'lib/engine/temporal-router.ts',['cell-responses','ida-headband'],'biology'),
 d('ida-headband','IDA · EEG laboratory','Brain in the jar','Explore task-conditioned EEG distance, residue, switching and recovery.','Local EEG research workbench','/ida/workbench/index.html','public/ida/workbench/core.js',['resource-ledger','attention-bench','human-atlas']),
 d('cell-responses','Cell response observatory','Microscope','Predict, reveal and compare recorded gene responses.','Recorded assay data','/cell','components/observatory/CellExplorer.tsx',['genome-planner','resource-ledger']),
 d('human-atlas','Human condition','Anatomical chart','Explore anatomy, pathways, life history and temporal state.','Educational systems explorer','/human','components/observatory/HumanConditionLab.tsx',['ida-headband','recovery-archive']),
 d('genome-planner','Genome request planner','Specimen drawer','Prepare a variant and context request. No live Atlas score is supplied.','Request planner','/?embedded=1&expedition=genome#expeditions','components/observatory/Expeditions.tsx',['cell-responses']),
 d('reactor-console','TAO reactor','Reactor controls','Disturb a simulated system and compare recovery controllers.','Control simulation','/?embedded=1#tao','components/observatory/TaoLab.tsx',['controller-comparison','recovery-archive']),
 d('controller-comparison','Controller comparison','Panel meters','Compare seeded controllers against conventional baselines.','Seeded simulation',undefined,'lib/engine/tao.ts',['reactor-console'],'dynamics'),
 d('instrument-dock','Instrument dock','Patch bay','Connect a supported local adapter and inspect its source and clock.','Local measurement interface','/?embedded=1#instrument','components/observatory/InstrumentDock.tsx',['ida-headband']),
 d('attention-bench','Attention & response','Response buttons','A consent-based, 24-trial timing experiment in this browser.','Local behavioural measurement','/?embedded=1#behaviour','components/observatory/BehaviourLab.tsx',['ida-headband','recovery-archive']),
 d('recovery-archive','Recovery archive','Reel recorder','Reveal futures in recorded cases and compare what each history predicts.','Recorded cases','/recovery','components/observatory/RecoveryLab.tsx',['attention-bench','earth-observations']),
 d('chemistry-bench','Reaction workbench','Sealed fume cupboard','Define a reaction, assay, competing mechanisms and baseline before opening this instrument. Related biochemical and quantum models are already available below.','Under construction',undefined,'research/Next_Observatory_Experiment.md',['resource-ledger','quantum-reference']),
 d('earth-observations','Earth observations','Field map','Retrieve Oslo station observations with source clocks, quality flags and replay.','Public observations','/?embedded=1&expedition=earth#expeditions','components/observatory/Expeditions.tsx',['forecast-ledger','public-statistics']),
 d('forecast-ledger','Forecast ledger','Chart recorder','Inspect existing forecast evidence and its held-out-period requirements.','Forecast evidence ledger','/workbenches/forecast','components/observatory/ForecastLedger.tsx',['earth-observations']),
 d('sky-survey','Sky survey','Brass telescope','Select a public survey, calibration record and discriminating test before adding a sky instrument.','Under construction',undefined,'research/Observatory_Room_Architecture.md',['encyclopedia']),
 d('reasoning-ledger','Nouns, verbs & dependencies','Punched-card reader','Inspect declared facts, assumptions, proof dependencies and missing premises.','Bounded logical rules','/workbenches/reasoning','lib/engine/reasoning.ts',['motion-learning','context-replay']),
 d('motion-learning','Learning workbench','Learning register','Compare a finite family of motion models, seek informative tests and revoke failed models.','Bounded model-family experiment','/workbenches/learning','lib/engine/learning-session.ts',['reasoning-ledger','adaptive-families']),
 d('adaptive-families','Adaptive families','Shared-world display','Watch six synthetic learners and inspect their actual updates.','Synthetic adaptation','/families','components/observatory/FamilyWorldLab.tsx',['motion-learning']),
 d('context-replay','Context & verification','Tape archive','Replay context changes and determine which checks need reassessment.','Recorded verification replay','/active-context','components/observatory/ActiveContext.tsx',['reasoning-ledger','memory-benchmark']),
 d('memory-benchmark','Memory benchmark','Memory reel','Inspect held-out POPGym results against observation-only and unrelated-history controls.','Executed benchmark records','/?embedded=1&expedition=memory#expeditions','components/observatory/Expeditions.tsx',['context-replay']),
 d('public-statistics','Public statistics','Statistical plotter','Fetch supported World Bank series, align observations and inspect correlation stress checks.','Sourced statistical comparison','/workbenches/statistics','lib/data-investigation.ts',['earth-observations','encyclopedia']),
 d('social-mechanisms','Social mechanisms','Census cabinet','Future causal models need defined populations, outcomes and identification assumptions.','Under construction',undefined,'research/Observatory_Room_Architecture.md',['public-statistics']),
 d('encyclopedia','Encyclopedia','Manuscript lectern','Read claims with their evidence, scope and unresolved questions.','Research records','/encyclopedia','app/encyclopedia/page.tsx',['programme-atlas','logbook']),
 d('programme-atlas','Programme atlas','Microfilm reader','Follow connections between the programme’s projects and scales.','Programme map','/atlas','components/observatory/ResearchAtlas.tsx',['encyclopedia','project-cabinet']),
 d('project-cabinet','All projects & source','Card catalogue','Find repositories, papers, specialist deliverables and publication status.','Project inventory','/projects','app/projects/page.tsx',['programme-atlas','agent-interface']),
 d('logbook','Your experiment logbook','Laboratory register','Inspect and export experiments retained in this browser.','Local records','/?embedded=1#logbook','components/observatory/Logbook.tsx',['encyclopedia']),
 d('agent-interface','Agent interface','Reference shelves','Read the central inquiry contract and discover executable capabilities.','Machine-readable interface','/agents','app/agents/page.tsx',['temporal-grammar','reasoning-ledger']),
];
export const SCIENCE_ROOMS:ScienceRoom[]=[
 {id:'mathematics',name:'Mathematics',title:'The Proof Room',description:'Exact operations, brass instruments and a notebook full of conditions.',disciplines:['Mathematics','Statistics','Logic','Temporal grammar'],image:'/images/precision-workbench.webp',accent:'#dec18c',station:'paper',devices:[p('ordered-model',20,66,25,19),p('paper-challenges',62,67,24,19),p('temporal-grammar',53,31,18,23)]},
 {id:'physics',name:'Physics',title:'The Quantum Chamber',description:'An optical bench, a cat under glass and the question of measurement.',disciplines:['Physics','Quantum mechanisms','Optics','Mechanics'],image:'/images/quantum-chamber.png',accent:'#bdb5f6',station:'scope',devices:[p('quantum-reference',74,38,21,29),p('quantum-beacon',26,43,22,20),p('schrodinger-cabinet',51,31,18,34)]},
 {id:'biology',name:'Biology',title:'The Biological Surgery',description:'Living systems, surgical tiles and a brain waiting under glass.',disciplines:['Biology','Neuroscience','Biochemistry','Genetics','Anatomy'],image:'/images/biology-surgery-room.png',accent:'#bfd1ab',station:'clinical',devices:[p('ida-headband',64,14,13,30),p('resource-ledger',36,59,26,22),p('cell-responses',45,32,15,23),p('human-atlas',24,13,20,27),p('genome-planner',78,55,18,21)]},
 {id:'engineering',name:'Engineering & dynamics',title:'The Control Room',description:'Meters, patch cables and a reactor that must earn its recovery.',disciplines:['Engineering','Control theory','Dynamical systems'],image:'/images/room-engineering.png',accent:'#efc17b',station:'amber',devices:[p('reactor-console',56,22,16,24),p('controller-comparison',7,15,27,22),p('instrument-dock',79,19,18,30)]},
 {id:'psychology',name:'Psychology',title:'The Response Study',description:'A red chair, a metronome and the pause between signal and response.',disciplines:['Psychology','Cognitive science','Behaviour'],image:'/images/room-psychology.png',accent:'#e2a3a6',station:'reel',devices:[p('attention-bench',79,48,18,13),p('recovery-archive',6,23,14,19)]},
 {id:'chemistry',name:'Chemistry',title:'The Reaction Laboratory',description:'The glassware is unpacked. The first reaction protocol is being prepared.',disciplines:['Chemistry','Materials science'],image:'/images/room-chemistry.png',accent:'#d8a779',station:'paper',construction:true,devices:[p('chemistry-bench',7,13,24,36)]},
 {id:'earth',name:'Earth & environment',title:'The Field Station',description:'Maps, rock trays and time-stamped observations from beyond the walls.',disciplines:['Earth science','Environment','Geography','Climate'],image:'/images/room-earth.png',accent:'#b0c8a4',station:'reel',devices:[p('earth-observations',18,4,29,27),p('forecast-ledger',14,29,23,18)]},
 {id:'astronomy',name:'Astronomy',title:'The Upper Dome',description:'The telescope is waiting. First come the survey, calibration and a test.',disciplines:['Astronomy','Astrophysics','Cosmology'],image:'/images/room-astronomy.png',accent:'#b7c0f5',station:'scope',construction:true,devices:[p('sky-survey',49,10,33,32)]},
 {id:'computing',name:'Computing & adaptation',title:'The Machine Room',description:'Punched cards, turning reels and machines that must show what they learned.',disciplines:['Computer science','AI','Information theory','Adaptive systems'],image:'/images/room-computing.png',accent:'#ebbd83',station:'teletype',devices:[p('reasoning-ledger',1,52,25,26),p('motion-learning',68,50,30,37),p('adaptive-families',67,15,15,30),p('context-replay',5,11,14,26),p('memory-benchmark',31,15,30,16)]},
 {id:'social',name:'Social science & economics',title:'The Statistical Office',description:'World maps, census drawers and a plotter asking what the numbers mean.',disciplines:['Economics','Sociology','Demography','Political science'],image:'/images/room-social.png',accent:'#dfb49e',station:'paper',devices:[p('public-statistics',79,30,21,29),p('social-mechanisms',1,14,17,31)]},
 {id:'archive',name:'Research archive',title:'The Reading Room',description:'Every result beside its conditions and the evidence that could change it.',disciplines:['Cross-disciplinary research','Scientific method','Programme records'],image:'/images/room-archive.png',accent:'#d4c592',station:'paper',devices:[p('encyclopedia',62,43,22,21),p('programme-atlas',83,30,14,19),p('project-cabinet',4,63,17,19),p('logbook',84,65,16,18),p('agent-interface',2,4,22,35)]},
];
export const ROOM_ALIASES:Record<string,string>={quantum:'physics',dynamics:'engineering',temporal:'mathematics',encyclopedia:'archive','quantum-chamber':'physics','biology-surgery':'biology','mathematics-desk':'mathematics','control-room':'engineering'};
export const available=(device:Device)=>Boolean(device.href||device.branch);
export function resolveRoom(id:string,rooms:ScienceRoom[]=SCIENCE_ROOMS):ScienceRoom|undefined{const seen=new Set<string>();let current=ROOM_ALIASES[id]??id;while(!seen.has(current)){seen.add(current);const room=rooms.find(r=>r.id===current);if(!room)return;if(!room.mergedInto)return room;current=room.mergedInto;}}
export function roomForDevice(id:string,rooms:ScienceRoom[]=SCIENCE_ROOMS){const room=rooms.find(r=>r.devices.some(p=>p.device===id));return room?resolveRoom(room.id,rooms):undefined;}
export function devicesForRoom(id:string,rooms:ScienceRoom[]=SCIENCE_ROOMS){return rooms.filter(r=>resolveRoom(r.id,rooms)?.id===id).flatMap(r=>r.devices.map(placement=>({placement,spatial:r.id===id,device:DEVICES.find(d=>d.id===placement.device)!})));}
export function catalogueIssues(rooms:ScienceRoom[]=SCIENCE_ROOMS,devices:Device[]=DEVICES):string[]{const issues:string[]=[],placed=new Map<string,number>();for(const room of rooms){if(!resolveRoom(room.id,rooms))issues.push(`Invalid or cyclic room merge: ${room.id}`);for(const spot of room.devices){placed.set(spot.device,(placed.get(spot.device)??0)+1);if(!devices.some(d=>d.id===spot.device))issues.push(`Unknown device: ${spot.device}`);if(spot.x<0||spot.y<0||spot.w<=0||spot.h<=0||spot.x+spot.w>100||spot.y+spot.h>100)issues.push(`Invalid hotspot: ${spot.device}`);}}for(const d of devices){if(placed.get(d.id)!==1)issues.push(`Device must have one home: ${d.id}`);for(const id of d.related)if(!devices.some(v=>v.id===id))issues.push(`Broken cross-reference: ${d.id} → ${id}`);}if(new Set(devices.map(d=>d.id)).size!==devices.length)issues.push('Duplicate device identity');if(new Set(rooms.map(r=>r.id)).size!==rooms.length)issues.push('Duplicate room identity');return issues;}
