// Authored source briefs, not generated discoveries. AI may cite these records;
// their scope and evidence class travel with every answer.
export const RESEARCH_SOURCES = [
  { id: 'S-MATH', branch: 'mathematics', title: 'UHL and bounded composition: premises and counterexamples', evidence: 'conditional mathematics', href: 'https://github.com/thantiklermcirony/empirical-observatory/releases/tag/laboratory-sources-2026-09-12', finding: 'T_u(x)=(x+u)/(1+xu) preserves the open interval (-1,1) for x,u in that interval. This establishes a property of the declared law. Boundedness alone does not select this law, the artanh coordinate, or a physical meaning for x; a projective premise or other selector is additional.' },
  { id: 'S-BIO', branch: 'biology', title: 'Redox resources: a recovered fraction can conceal depleted reserves', evidence: 'conditional resource accounting; synthetic examples', href: 'https://github.com/thantiklermcirony/empirical-observatory/releases/tag/laboratory-sources-2026-09-12', finding: 'Under fixed volume, nonnegative pools and declared GPx/GR stoichiometry and supply, GSH/2 + NADPH defines a necessary resource budget. A high reduced fraction does not identify the absolute pool or reserve. Excluding a target by the budget is meaningful; a target below the ceiling is not thereby attained, and no survival conclusion follows.' },
  { id: 'S-OBS', branch: 'biology', title: 'Observation bridge and calibration limits', evidence: 'published-data audit and candidate observation adapter', href: 'https://github.com/thantiklermcirony/empirical-observatory/releases/tag/laboratory-sources-2026-09-12', finding: 'The preserved Biology Observation Bridge does not establish endogenous extraction survival from extract-spike standards, nor provide every matched absolute NADPH, compartment-volume and later-outcome observation needed for biological transfer. Relative weight within a rejected model family cannot justify a recommendation.' },
  { id: 'S-TIME', branch: 'temporal', title: 'Temporal grammar: operation order and observation identity', evidence: 'reviewed routing software and exact declared-model calculations', href: 'https://github.com/thantiklermcirony/empirical-observatory/tree/main/automation/temporal-grammar', finding: 'Ordered actions, preparation identity, clock, units and premises are retained. A corrected observation at the same time is different from a later measurement. Removing a required premise blocks the affected inference; an unsupported cross-domain transformation stays unresolved.' },
  { id: 'S-ADAPT', branch: 'adaptation', title: 'Adaptation needs a perturbation, objective and comparison', evidence: 'operational definition and synthetic controller benchmark', href: 'https://github.com/thantiklermcirony/empirical-observatory/blob/main/research/Methods.md', finding: 'In this observatory, a claim of adaptive improvement needs a defined perturbation, observable objective, time horizon and comparison at equal information and action cost. Merely changing or staying inside bounds is insufficient. Short-term regulation, learning and evolutionary adaptation are different mechanisms and timescales.' },
  { id: 'S-DYN', branch: 'dynamics', title: 'TAO versus conventional feedback', evidence: 'seeded simulation, not a biological experiment', href: 'https://github.com/thantiklermcirony/empirical-observatory/blob/main/research/Methods.md', finding: 'The published synthetic reactor comparison retains clipped linear, PI and sigmoid baselines. PI has the best mean absolute error in the original held-out comparison. TAO does not dominate all metrics. Recompute the current declared fixture before reporting its numerical results.' },
  { id: 'S-QUANTUM', branch: 'quantum', title: 'Quantum reaction reference and transfer boundary', evidence: 'dimensionless numerical reference under declared premises', href: 'https://github.com/thantiklermcirony/empirical-observatory/blob/main/lib/engine/quantum-reference.ts', finding: 'The four-level reference can compute reaction yields under its state, Hamiltonian, rates and measurement protocol. Its clock is dimensionless. Coherent evolution requires state and instrument information; scalar UHL conditioning is a restricted sector. No calibrated transfer to biological adaptation or survival is established.' },
  { id: 'S-NEXT', branch: 'encyclopedia', title: 'Next experiment: distinguish apparent recovery from resource recovery', evidence: 'prospective protocol; not executed', href: 'https://github.com/thantiklermcirony/empirical-observatory/blob/main/research/Next_Observatory_Experiment.md', finding: 'The next proposed challenge compares observation sufficiency and calibrated resource-ledger inference at equal assay cost, with held-out cases, coverage checks and predefined success/failure gates. Biological outcome claims require a separate matched-data readiness gate.' },
] as const;

export const RESEARCH_BRANCHES = [
  { id: 'mathematics', title: 'Mathematics & boundedness' },
  { id: 'temporal', title: 'Temporal grammar' },
  { id: 'adaptation', title: 'Adaptation' },
  { id: 'biology', title: 'Biology' },
  { id: 'dynamics', title: 'Dynamics & control' },
  { id: 'quantum', title: 'Quantum mechanisms' },
  { id: 'encyclopedia', title: 'Encyclopedia' },
] as const;
export type ResearchBranchId = typeof RESEARCH_BRANCHES[number]['id'];
