import { TEST_IDS, type FrameworkTestId } from './framework-tests.ts';
export type ClaimClass = 'established-reference' | 'conditional-model' | 'programme-hypothesis' | 'open-question';
export type ScienceClaim = { id: string; title: string; classification: ClaimClass; branch: 'physics' | 'biology'; layer: 'mechanics' | 'bioelectric' | 'quantum' | 'resources'; entities: string[]; statement: string; scope: string; why: string; alternative: string; missing: string[]; equation?: string; sourceIds: string[]; testIds: FrameworkTestId[]; deviceIds: string[]; revision: number };
export const FRAMEWORK_VERSION = 'living-framework/1';
export const CLAIM_LABELS: Record<ClaimClass,string> = { 'established-reference':'Established within stated scope', 'conditional-model':'Conditional model', 'programme-hypothesis':'Programme hypothesis', 'open-question':'Open question' };
export const FRAMEWORK_SOURCES = [
 { id:'hh1952',title:'Hodgkin & Huxley (1952) · Membrane current and excitation',url:'https://pubmed.ncbi.nlm.nih.gov/12991237/',kind:'Primary electrophysiology and model; squid giant axon' },
 { id:'eyal2016',title:'Eyal et al. (2016) · Human neocortical membrane properties',url:'https://elifesciences.org/articles/16553',kind:'Primary measurements and models; sampled cortical neurons' },
 { id:'luo1991',title:'Luo & Rudy (1991) · Ventricular cardiac action potentials',url:'https://pubmed.ncbi.nlm.nih.gov/1709839/',kind:'Primary cardiac-cell model; stated preparation and currents' },
 { id:'zhao2006',title:'Zhao et al. (2006) · Electrical signals and wound healing',url:'https://pubmed.ncbi.nlm.nih.gov/16871217/',kind:'Primary experimental study; cell migration and signalling' },
 { id:'pai2012',title:'Pai et al. (2012) · Voltage and eye patterning in Xenopus',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3243095/',kind:'Primary developmental experiment; organism-specific finding' },
 { id:'feynman-motion', title:'Feynman Lectures I.9 · Newton’s laws of dynamics', url:'https://www.feynmanlectures.caltech.edu/I_09.html', kind:'Established physics reference' },
 { id:'feynman-charge', title:'Feynman Lectures II.27 · Field energy and momentum', url:'https://www.feynmanlectures.caltech.edu/II_27.html', kind:'Established physics reference' },
 { id:'feynman-circuit', title:'Feynman Lectures II.22 · AC circuits', url:'https://www.feynmanlectures.caltech.edu/II_22.html', kind:'Established physics reference' },
 { id:'feynman-quantum', title:'Feynman Lectures III.3 · Probability amplitudes', url:'https://www.feynmanlectures.caltech.edu/III_03.html', kind:'Established physics reference' },
 { id:'project-math', title:'Declared bounded operations and their premises', url:'https://github.com/thantiklermcirony/empirical-observatory/blob/main/lib/engine/temporal-router.ts', kind:'Programme implementation; conditional mathematics' },
 { id:'project-quantum', title:'Four-level quantum reference', url:'https://github.com/thantiklermcirony/empirical-observatory/blob/main/lib/engine/quantum-reference.ts', kind:'Programme implementation; dimensionless model' },
 { id:'project-experiment', title:'Prospective resource-recovery experiment', url:'https://github.com/thantiklermcirony/empirical-observatory/blob/main/research/Next_Observatory_Experiment.md', kind:'Prospective protocol; not empirical validation' },
];
export const BODY_SYSTEMS = [
 {id:'nervous',name:'Nervous system',entity:'brain',devices:['ida-headband']}, {id:'cardiac',name:'Cardiovascular system',entity:'heart',devices:[]},
 {id:'respiratory',name:'Respiratory system',entity:'lung',devices:[]}, {id:'digestive',name:'Digestive system',entity:'gut',devices:[]},
 {id:'integumentary',name:'Skin and barriers',entity:'skin',devices:[]}, {id:'muscular',name:'Muscular system',entity:'muscle',devices:[]},
 {id:'skeletal',name:'Skeletal system',entity:'bone',devices:[]}, {id:'arterial',name:'Arterial system',entity:'vessels',devices:[]}, {id:'venous',name:'Venous system',entity:'vessels',devices:[]}, {id:'connective',name:'Connective tissues',entity:'connective',devices:[]},
 {id:'lymphatic',name:'Lymphatic system',entity:'lymph',devices:[]}, {id:'endocrine',name:'Endocrine system',entity:'endocrine',devices:[]},
 {id:'urinary',name:'Urinary system',entity:'kidney',devices:[]}, {id:'reproductive',name:'Reproductive system',entity:'reproductive',devices:[]},
 {id:'sensory',name:'Sensory organs',entity:'sensory',devices:[]},
];
export const SCIENCE_CLAIMS: ScienceClaim[] = [
 {id:'B-NEURAL',title:'Membrane currents support neural signalling',classification:'established-reference',branch:'biology',layer:'bioelectric',entities:['brain','sensory'],statement:'Ionic conductances and membrane capacitance participate in neural electrical signalling. Specific channel kinetics and parameters depend on cell type and preparation.',scope:'Classic squid-axon findings and separately studied human cortical membrane properties; these are not interchangeable calibrations.',why:'This supplies a measurable bridge from physics to neural tissue: current, voltage, capacitance and time.',alternative:'An EEG trace is an aggregate measurement with artefacts; it does not identify every neuron or a mental state.',missing:['Cell or tissue preparation, electrode geometry and calibration.','A forward observation model before relating membrane dynamics to scalp EEG.'],equation:'I = Cₘ dV/dt + Σ I_ion',sourceIds:['hh1952','eyal2016'],testIds:['passive-membrane'],deviceIds:['ida-headband'],revision:1},
 {id:'B-CARDIAC',title:'Ionic currents shape cardiac voltage',classification:'established-reference',branch:'biology',layer:'bioelectric',entities:['heart'],statement:'Cardiac action-potential models account for ionic currents and membrane voltage. Tissue propagation and mechanical contraction require additional coupled models.',scope:'The cited ventricular-cell model has its own species, currents and parameter assumptions. The anatomical atlas supplies geometry labels, not these parameters.',why:'It connects a selected heart structure to measurable electrical variables and an established modelling tradition.',alternative:'A passive RC model cannot explain the full active cardiac action potential; an organ-wide field cannot be inferred from one cell model.',missing:['Specific cell type, species and parameter provenance.','Tissue conductivity, geometry, coupling and independent observations.'],sourceIds:['luo1991'],testIds:[],deviceIds:[],revision:1},
 {id:'B-WOUND',title:'Electrical cues can influence wound-cell migration',classification:'established-reference',branch:'biology',layer:'bioelectric',entities:['skin'],statement:'The cited experiments connect electrical cues to directional cell migration and signalling during wound healing.',scope:'The preparations and interventions studied by Zhao and colleagues. This is not a universal tissue-repair law.',why:'It is a concrete non-neural bioelectric mechanism with experiments, rather than an assumed field overlay.',alternative:'Chemical gradients, mechanics and inflammatory signalling may also contribute; their roles require controlled comparison.',missing:['A specified tissue and injury model.','Matched field, migration and signalling measurements with controls.'],sourceIds:['zhao2006'],testIds:[],deviceIds:['cell-responses'],revision:1},
 {id:'H-PATTERN',title:'Can voltage-state models explain more tissue patterning?',classification:'programme-hypothesis',branch:'biology',layer:'bioelectric',entities:['skin','brain','sensory'],statement:'Extend specific experimental bioelectric patterning findings to a carefully chosen new tissue only after a discriminating test.',scope:'Pai and colleagues studied eye patterning in Xenopus. Extension to human organs is a proposal.',why:'Specific voltage manipulations affected a developmental outcome in that preparation.',alternative:'The result may depend on organism, developmental stage, channel expression and downstream molecular pathways.',missing:['A target tissue, causal intervention and appropriate controls.','A prediction different from the conventional developmental model.','Independent replication in the new domain.'],sourceIds:['pai2012'],testIds:[],deviceIds:['cell-responses'],revision:1},
 {id:'P-MOTION',title:'Forces change momentum',classification:'established-reference',branch:'physics',layer:'mechanics',entities:['physics','muscle','bone','heart'],statement:'In an inertial frame, Newtonian dynamics relates net force to the rate of change of momentum. For constant mass this becomes F=ma.',scope:'Classical mechanics; an inertial frame and an adequate system boundary. Relativistic and quantum regimes need other models.',why:'This is the conventional baseline against which a proposed mechanical law must be compared.',alternative:'An apparent anomaly can result from an omitted force, moving frame or measurement error.',missing:['A selected physical system, measured forces, mass, motion and uncertainty.'],equation:'F = dp/dt; constant mass: F = ma',sourceIds:['feynman-motion'],testIds:[],deviceIds:['motion-learning'],revision:1},
 {id:'P-CHARGE',title:'Electric charge is locally conserved',classification:'established-reference',branch:'physics',layer:'bioelectric',entities:['physics','brain','heart','skin','muscle','kidney','vessels'],statement:'Charge accumulating in a region must be accounted for by current through its boundary.',scope:'Electromagnetic charge accounting; electrical current is a measurable transport quantity.',why:'Any proposed bioelectric mechanism must obey charge accounting and identify carriers, boundaries and time.',alternative:'A recorded voltage can include electrode drift, motion artefacts or unmodelled ionic currents.',missing:['Geometry, conductivity, boundary conditions and calibrated electrical observations for the selected tissue.'],equation:'∂ρ/∂t + ∇·J = 0',sourceIds:['feynman-charge'],testIds:[],deviceIds:['ida-headband'],revision:1},
 {id:'P-RC',title:'Passive electrical response',classification:'conditional-model',branch:'physics',layer:'bioelectric',entities:['physics','brain','heart','muscle'],statement:'A resistor-capacitor model predicts relaxation of a passive membrane voltage after a current step.',scope:'A lumped, passive circuit with constant resistance and capacitance. It does not simulate a whole organ.',why:'A simple analytic baseline makes numerical errors visible before adding active channels or tissue coupling.',alternative:'Voltage-gated channels, spatial effects or changing conductance may make this model inadequate.',missing:['Measured resistance, capacitance and current protocol for the actual preparation.'],equation:'C dV/dt = −(V−E_L)/R + I',sourceIds:['feynman-circuit'],testIds:['passive-membrane'],deviceIds:['ida-headband'],revision:1},
 {id:'P-BORN',title:'Quantum probabilities require a state and measurement',classification:'established-reference',branch:'physics',layer:'quantum',entities:['physics'],statement:'For a normalized state and specified measurement basis, squared probability-amplitude magnitude gives the outcome probability.',scope:'A specified quantum state, evolution and measurement. An anatomical picture does not provide these inputs.',why:'Quantum claims require an actual state and instrument model, not only the word quantum.',alternative:'A classical or incoherent rate model may explain a measured effect without the proposed coherence.',missing:['State preparation, Hamiltonian, measurement operators and calibration for an application.'],equation:'P(outcome i) = |⟨i|ψ⟩|²',sourceIds:['feynman-quantum'],testIds:[],deviceIds:['quantum-reference','quantum-beacon'],revision:1},
 {id:'H-UHL',title:'Where does UHL describe a physical operation?',classification:'programme-hypothesis',branch:'physics',layer:'mechanics',entities:['physics'],statement:'The declared bounded composition law may represent particular physical operations when additional selecting premises and calibration are justified.',scope:'No universal physical law is admitted. Boundedness by itself does not select this composition.',why:'The law preserves bounds and has useful exact composition structure; physical applicability is an additional question.',alternative:'Other bounded composition laws share closure, identity and associativity. Ordinary calibrated models remain the baseline.',missing:['A physical observable and intervention map.','An additional law-selecting premise.','Held-out measurements that distinguish the alternative laws.'],equation:'A(x,u)=(x+u)/(1+xu)',sourceIds:['project-math'],testIds:['bounded-selector'],deviceIds:['ordered-model','paper-challenges'],revision:1},
 {id:'B-RESOURCE',title:'A recovered fraction can hide depleted reserves',classification:'conditional-model',branch:'biology',layer:'resources',entities:['cell'],statement:'A reduced fraction alone does not identify absolute resource stocks. A declared stoichiometric ledger gives a necessary ceiling on reaction extent.',scope:'Fixed-volume synthetic GPx/GR accounting. No organ, survival or disease prediction follows.',why:'Two preparations can share a fraction while having different absolute pools.',alternative:'A conventional calibrated resource ledger may perform as well as the proposed measurement selector.',missing:['Matched absolute pools, assay calibration, supply and outcome measurements.'],equation:'C = qT/2 + N + J',sourceIds:['project-math','project-experiment'],testIds:[],deviceIds:['resource-ledger','cell-responses'],revision:1},
 {id:'H-QUANTUM-BIO',title:'Which quantum mechanisms matter in this tissue?',classification:'open-question',branch:'biology',layer:'quantum',entities:['brain','heart','skin','muscle','lung','gut','kidney','bone','immune','lymph','endocrine','reproductive','sensory','vessels','connective'],statement:'Map specific molecular mechanisms and measurements before attaching a quantum model to a tissue. The Observatory has no calibrated organ-wide quantum-field map.',scope:'An explicit coverage gap. The existing four-level reference is a separate dimensionless model.',why:'Chemical processes have quantum foundations; a useful tissue-level claim additionally needs a specific mechanism and distinguishable prediction.',alternative:'Classical coarse-grained or incoherent models may already explain the observations.',missing:['Molecular species and compartment.','Measured preparation, rates and physical clock.','A discriminating observation against a classical or incoherent baseline.'],sourceIds:['project-quantum'],testIds:[],deviceIds:['quantum-reference'],revision:1},
];
export const FRAMEWORK_REVISIONS = [{id:'framework-001',date:'2026-09-12',description:'Established physics references, conditional calculations and programme hypotheses receive separate identities. Biology begins from the preserved anatomical atlas.',evidence:'Authored registry with linked sources. No new empirical discovery admitted.'}];
export function claimsForEntity(entity:string){ return SCIENCE_CLAIMS.filter(c=>c.entities.includes(entity)); }
export function registryIssues(){const ids=new Set(SCIENCE_CLAIMS.map(c=>c.id)), sources=new Set(FRAMEWORK_SOURCES.map(s=>s.id));const issues:string[]=[];if(ids.size!==SCIENCE_CLAIMS.length)issues.push('Duplicate claim identity');for(const c of SCIENCE_CLAIMS){for(const s of c.sourceIds)if(!sources.has(s))issues.push(`${c.id}: unknown source ${s}`);for(const t of c.testIds)if(!TEST_IDS.includes(t))issues.push(`${c.id}: unknown test ${t}`);if(c.classification==='programme-hypothesis'&&(!c.alternative||!c.missing.length))issues.push(`${c.id}: hypothesis needs alternative and missing evidence`);}return issues;}

// Curated concept associations, verified against the preserved BodyParts3D atlas.
// Mesh display groups can include vessels and supporting tissues; they do not define an organ's identity.
export const BODY_CONCEPT_SYSTEMS:Record<string,string>={FMA50801:'nervous',FMA7088:'cardiac',FMA7197:'digestive',FMA7148:'digestive',FMA7196:'lymphatic',FMA7198:'digestive',FMA15900:'urinary',FMA7394:'respiratory'};
export function resolveAnatomySystem(id:string,systems:string[],fallback:string){return BODY_CONCEPT_SYSTEMS[id]??(systems.length===1?systems[0]:systems.length?'mixed':fallback);}
