/** Coverage scaffold, adapted from OECD Revised FOS (2007), Annex 1. Not a claim of complete scientific knowledge. */
export const FIELD_SOURCE='https://one.oecd.org/document/DSTI/EAS/STP/NESTI(2006)19/FINAL/en/pdf';
export const FIELD_GROUPS=['Natural sciences','Engineering and technology','Medical and health sciences','Agricultural sciences','Social sciences','Humanities and scientific methods'];
export type ScienceField={id:string;label:string;room:string;scope:string};
const f=(id:string,label:string,room:string,scope:string):ScienceField=>({id,label,room,scope});
export const SCIENCE_FIELDS:ScienceField[]=[
 f('1.1','Mathematics','mathematics','Logic, geometry, algebra, analysis, probability and statistics'),
 f('1.2','Computer and information sciences','computing','Computation, information, algorithms and formal systems'),
 f('1.3','Physical sciences','physics','Mechanics, fields, matter, thermodynamics, optics, particles and astronomy'),
 f('1.4','Chemical sciences','chemistry','Species, reactions, structure, kinetics and chemical measurement'),
 f('1.5','Earth and environmental sciences','earth','Geology, climate, atmosphere, oceans and hydrology'),
 f('1.6','Biological sciences','biology','Cells, organisms, evolution, ecology, genetics and molecular systems'),
 f('1.7','Other natural sciences','archive','Explicit intake for natural-science work not yet classified'),
 f('2.1','Civil engineering','engineering','Structures, transport and built environments'),
 f('2.2','Electrical and information engineering','engineering','Circuits, communication, electronics and control'),
 f('2.3','Mechanical engineering','engineering','Mechanical systems, energy conversion and reliability'),
 f('2.4','Chemical engineering','chemistry','Processes, reactors and transport'),
 f('2.5','Materials engineering','chemistry','Material structure, properties and processing'),
 f('2.6','Medical engineering','medicine','Instrument design and measurement; validation required for applications'),
 f('2.7','Environmental engineering','earth','Environmental systems, resources and engineered interventions'),
 f('2.8','Environmental biotechnology','biology','Biological environmental processes'),
 f('2.9','Industrial biotechnology','engineering','Bioprocesses and biological production'),
 f('2.10','Nanotechnology','physics','Nanoscale structures and processes'),
 f('2.11','Other engineering','engineering','Explicit intake for unclassified engineering'),
 f('3.1','Basic medicine','medicine','Anatomy, physiology, neuroscience and pharmacology'),
 f('3.2','Clinical medicine','medicine','Specified populations, interventions and clinical outcomes'),
 f('3.3','Health sciences','medicine','Epidemiology, nutrition and population health'),
 f('3.4','Medical biotechnology','medicine','Biological technologies in health contexts'),
 f('3.5','Other medical sciences','medicine','Explicit intake for unclassified medical research'),
 f('4.1','Agriculture, forestry and fisheries','agriculture','Crops, soil, forests and aquatic production'),
 f('4.2','Animal and dairy science','agriculture','Animal production systems'),
 f('4.3','Veterinary science','agriculture','Animal health with species-specific evidence'),
 f('4.4','Agricultural biotechnology','agriculture','Biological technologies for agricultural systems'),
 f('4.5','Other agricultural sciences','agriculture','Explicit intake for unclassified agricultural research'),
 f('5.1','Psychology','psychology','Behaviour, cognition, attention and measured experience'),
 f('5.2','Economics and business','social','Economic systems, institutions and decisions'),
 f('5.3','Educational sciences','social','Learning, instruction and education systems'),
 f('5.4','Sociology','social','Populations, institutions and social interaction'),
 f('5.5','Law','social','Empirical study of legal institutions; normative claims remain distinct'),
 f('5.6','Political science','social','Collective decisions, governance and institutions'),
 f('5.7','Social and economic geography','social','Spatial patterns in populations and economic activity'),
 f('5.8','Media and communications','language','Information transmission, media and communication'),
 f('5.9','Other social sciences','social','Explicit intake for unclassified social research'),
 f('6.1','History and archaeology','archive','Source criticism, material evidence and historical inference'),
 f('6.2','Languages and literature','language','Scientific linguistics, corpora and language measurement; interpretation labelled separately'),
 f('6.3','Philosophy, ethics and religion','archive','Logic, philosophy of science and empirical studies; normative or metaphysical claims are not physical laws'),
 f('6.4','Arts research','archive','Empirical perception, acoustics and material studies; aesthetic judgements remain distinct'),
 f('6.5','Other humanities','archive','Explicit intake for historical, conceptual or methodological research'),
];
