import { LAB_EXAMPLES } from '@/lib/lab-contract';
import { labJson } from '@/lib/lab-http';
export function GET() { const inquiry = { type: 'object', required: 'identity question system observer quantities operations constraints mechanism premises execution results contrast next_question provenance'.split(' '), additionalProperties: false, properties: Object.fromEntries('identity question system observer quantities operations constraints mechanism premises execution results contrast next_question provenance'.split(' ').map(k => [k, {}])) };
  const request = { oneOf: [{ type: 'object', required: ['prompt'], additionalProperties: false, properties: { prompt: { type: 'string', minLength: 1, maxLength: 2000 } } }, { type: 'object', required: ['inquiry'], additionalProperties: false, properties: { inquiry, previous: { type: 'object', description: 'Caller-declared prior snapshot; not authenticated history' } } }] };
  const success = { description: 'Scoped result, not empirical validation', content: { 'application/json': { schema: { type: 'object', required: ['printout'], properties: { printout: { type: 'object' } } } } } };
  return labJson({ openapi: '3.1.0', info: { title: 'Empirical Observatory Inquiry', version: '1.0.0', description: 'Finite declared scientific operations. Full port schemas and working inquiries are returned by GET /api/inquiry.' }, servers: [{ url: 'https://empirical-observatory.madmanmuzza.chatgpt.site' }], paths: {
    '/api/inquiry/research': { post: { operationId: 'investigateQuestion', description: 'Plan across relevant branches, execute supported calculations and explain the actual evidence. Uses at most two shared AI calls; returns a labelled source brief when AI is unavailable. Running does not save.', requestBody: { required: true, content: { 'application/json': { schema: request.oneOf[0], example: { prompt: 'is biology bounded and adaptive, prove it' } } } }, responses: { '200': { description: 'Printout with research plan, answer, evidence-linked sections, exact calculation cases, sources, missing observations and optional signedReport save receipt.' }, '400': { description: 'Invalid question or JSON' }, '503': { description: 'Laboratory execution unavailable' } } } },
    '/api/inquiry': { get: { operationId: 'discoverCapabilities', responses: { '200': { description: 'Capabilities, limits and complete structured fixtures' } } }, post: { operationId: 'evaluateInquiry', requestBody: { required: true, content: { 'application/json': { schema: request, example: { prompt: LAB_EXAMPLES[0].prompt } } } }, responses: { '200': success, '400': { description: 'Invalid schema or JSON' }, '413': { description: 'Body over 64 KiB' }, '503': { description: 'Execution unavailable' } } } },
    '/api/inquiry/interpret': { get: { operationId: 'interpreterStatus', responses: { '200': { description: 'Readiness, provider, model and shared daily limit; never credentials' } } }, post: { operationId: 'interpretQuestion', requestBody: { required: true, content: { 'application/json': { schema: request.oneOf[0] } } }, responses: { '200': { description: 'Unverified proposal with inquiry, or needs_input with specific questions. Inspect before execution.' }, '400': { description: 'Invalid request or interpretation' }, '429': { description: 'Shared daily AI call limit reached' }, '503': { description: 'AI not configured or unavailable' } } } },
    '/api/inquiry/save': { post: { operationId: 'savePrivatePrintout', requestBody: { required: true, content: { 'application/json': { schema: { oneOf: [{ type: 'object', required: ['request'], additionalProperties: false, properties: { request: { oneOf: [...request.oneOf, { type: 'object', required: ['research'], additionalProperties: false, properties: { research: request.oneOf[0] } }] } } }, { type: 'object', required: ['signedReport'], additionalProperties: false, properties: { signedReport: { type: 'object', description: 'Exact server-issued save receipt returned by /api/inquiry/research; expires after one hour. Never construct or alter it.' } } }] } } } }, responses: { '201': { description: 'Verified exact AI printout or recomputed source printout, id, bearer token and expiry; no provider call' }, '400': { description: 'Invalid/expired receipt, invalid request or storage capacity reached' }, '413': { description: 'Save envelope exceeds 1,050,000 bytes' }, '503': { description: 'Storage unavailable' } } } },
    '/api/inquiry/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { operationId: 'readPrivatePrintout', security: [{ privateRecord: [] }], responses: { '200': success, '404': { description: 'Not found, expired or token invalid' } } }, delete: { operationId: 'deletePrivatePrintout', security: [{ privateRecord: [] }], responses: { '200': { description: 'Deleted' }, '404': { description: 'Not found or token invalid' } } } } }, components: { securitySchemes: { privateRecord: { type: 'http', scheme: 'bearer', description: 'Random 256-bit token returned for this record only' } } } }); }
