import { LAB_EXAMPLES } from '@/lib/lab-contract';
import { labJson } from '@/lib/lab-http';
export function GET() { const inquiry = { type: 'object', required: 'identity question system observer quantities operations constraints mechanism premises execution results contrast next_question provenance'.split(' '), additionalProperties: false, properties: Object.fromEntries('identity question system observer quantities operations constraints mechanism premises execution results contrast next_question provenance'.split(' ').map(k => [k, {}])) };
  const request = { oneOf: [{ type: 'object', required: ['prompt'], additionalProperties: false, properties: { prompt: { type: 'string', minLength: 1, maxLength: 2000 } } }, { type: 'object', required: ['inquiry'], additionalProperties: false, properties: { inquiry, previous: { type: 'object', description: 'Caller-declared prior snapshot; not authenticated history' } } }] };
  const success = { description: 'Scoped result, not empirical validation', content: { 'application/json': { schema: { type: 'object', required: ['printout'], properties: { printout: { type: 'object' } } } } } };
  return labJson({ openapi: '3.1.0', info: { title: 'Empirical Observatory Inquiry', version: '1.0.0', description: 'Finite declared scientific operations. Full port schemas and working inquiries are returned by GET /api/inquiry.' }, servers: [{ url: 'https://empirical-observatory.madmanmuzza.chatgpt.site' }], paths: {
    '/api/inquiry': { get: { operationId: 'discoverCapabilities', responses: { '200': { description: 'Capabilities, limits and complete structured fixtures' } } }, post: { operationId: 'evaluateInquiry', requestBody: { required: true, content: { 'application/json': { schema: request, example: { prompt: LAB_EXAMPLES[0].prompt } } } }, responses: { '200': success, '400': { description: 'Invalid schema or JSON' }, '413': { description: 'Body over 64 KiB' }, '503': { description: 'Execution unavailable' } } } },
    '/api/inquiry/interpret': { get: { operationId: 'interpreterStatus', responses: { '200': { description: 'Readiness, provider, model and shared daily limit; never credentials' } } }, post: { operationId: 'interpretQuestion', requestBody: { required: true, content: { 'application/json': { schema: request.oneOf[0] } } }, responses: { '200': { description: 'Unverified proposal with inquiry, or needs_input with specific questions. Inspect before execution.' }, '400': { description: 'Invalid request or interpretation' }, '429': { description: 'Shared daily AI call limit reached' }, '503': { description: 'AI not configured or unavailable' } } } },
    '/api/inquiry/save': { post: { operationId: 'savePrivatePrintout', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['request'], additionalProperties: false, properties: { request } } } } }, responses: { '201': { description: 'Recomputed printout, id, bearer token and expiry' }, '400': { description: 'Invalid request or storage capacity reached' }, '503': { description: 'Storage unavailable' } } } },
    '/api/inquiry/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { operationId: 'readPrivatePrintout', security: [{ privateRecord: [] }], responses: { '200': success, '404': { description: 'Not found, expired or token invalid' } } }, delete: { operationId: 'deletePrivatePrintout', security: [{ privateRecord: [] }], responses: { '200': { description: 'Deleted' }, '404': { description: 'Not found or token invalid' } } } } }, components: { securitySchemes: { privateRecord: { type: 'http', scheme: 'bearer', description: 'Random 256-bit token returned for this record only' } } } }); }
