import test from 'node:test';
import assert from 'node:assert/strict';
import {DEFAULTS,extractPowers,chart,ballDistance,residueStep,Recovery,gate,PacketAssembler,validateConfig} from '../../public/ida/workbench/core.js';
import {parseCSV} from '../../public/ida/workbench/csv.js';
const c={...DEFAULTS};
const wave=offset=>Array.from({length:1024},(_,i)=>Array.from({length:4},(_,j)=>offset+10*Math.sin(2*Math.PI*10*i/256+j)));
test('alpha sinusoid and DC invariance',()=>{const a=extractPowers(wave(0),c),b=extractPowers(wave(800),c);assert.ok(a.valid&&b.valid);assert.ok(a.powers[0][2]/a.powers[0].reduce((x,y)=>x+y,0)>.99);assert.ok(Math.abs(a.powers[0][2]-b.powers[0][2])<1e-8)});
test('flatline and excessive amplitude fail quality',()=>{assert.equal(extractPowers(Array.from({length:1024},()=>[800,800,800,800]),c).valid,false);assert.equal(extractPowers(wave(0).map(r=>r.map(x=>x*100)),c).valid,false)});
test('log odds is exactly twice rapidity',()=>{const p=Array.from({length:4},()=>[2,3,4,5]);const a=chart(p,'rapidity',c),b=chart(p,'log_odds',c);a.forEach((x,i)=>assert.ok(Math.abs(2*x-b[i])<1e-12))});
test('Poincare distance identity and symmetry',()=>{const a=[.1,.2],b=[-.2,.1];assert.equal(ballDistance(a,a,1),0);assert.ok(Math.abs(ballDistance(a,b,1)-ballDistance(b,a,1))<1e-12)});
test('residue exact half-life and partition invariance',()=>{assert.equal(residueStep(4,0,30,30),2);assert.ok(Math.abs(residueStep(0,3,10,30)-residueStep(residueStep(0,3,5,30),3,5,30))<1e-12)});
test('immature and interrupted return windows stay unavailable',()=>{const r=new Recovery(c,{distance:v=>v[0],deadband:1});assert.equal(r.update(0,[3]).return[5],null);for(let t=.5;t<=31;t+=.5)r.update(t,[3]);assert.equal(r.update(31.5,[3]).ready,true);const after=r.update(40,[3]);assert.equal(after.ready,false);assert.equal(after.segment,1)});
test('falling distance cannot authorize rising residue',()=>{assert.equal(gate({ready:true,residue:.1,return:{5:1,15:1,30:1},residue_trend:{5:.01,15:0,30:0}},true).decision,'reduce');assert.equal(gate(null,false).decision,'hold')});
test('packet alignment, rollover and missing packet detection',()=>{const rows=[],gaps=[];const p=new PacketAssembler(r=>rows.push(...r),g=>gaps.push(g));for(const index of [65535,0,2])for(const electrode of [2,0,3,1])p.push({index,electrode,samples:Array(12).fill(electrode),timestamp:index===65535?0:index===0?46.875:140.625});assert.equal(rows.length,36);assert.deepEqual(rows[0].values,[0,1,2,3]);assert.equal(gaps.length,1);assert.equal(gaps[0].lostPackets,1)});
test('unknown dials rejected',()=>{assert.throws(()=>validateConfig({health:1}));assert.throws(()=>validateConfig({fs:250}))});
const header='TimeStamp,RAW_TP9,RAW_AF7,RAW_AF8,RAW_TP10\n';
test('CSV preserves recording gaps',()=>{const csv=header+Array.from({length:1024},(_,i)=>`${i/256+(i>=512?.2:0)},1,2,3,4`).join('\n');const p=parseCSV(csv);assert.ok(p.rows[512].t-p.rows[511].t>.2)});
test('CSV reconstructs equal timestamp groups',()=>{const csv=header+Array.from({length:1024},(_,i)=>`${Math.floor(i/4)*4/256},1,2,3,4`).join('\n');const p=parseCSV(csv);assert.equal(p.rows[3].t,3/256);assert.equal(p.metadata.reconstructed_samples,1024)});
test('band-only CSV cannot masquerade as full raw EEG',()=>assert.throws(()=>parseCSV('TimeStamp,Alpha_TP9\n0,1')));
