'use client';
/* oxlint-disable next/no-html-link-for-pages -- Native links preserve the Observatory's existing navigation and source downloads. */
import {useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {ObservatoryHeader} from '@/components/observatory/LaboratoryIdentity';
import {CONTRIBUTIONS,ENGINE_STAGES,compositionGap,stationaryRing} from '@/lib/discovery-ledger';
import corpus from '@/lib/discovery-corpus.json';
import './discovery.css';

export default function Discoveries(){
 const [selected,setActive]=useState<string|null>(null),[a,setA]=useState(.5),[b,setB]=useState(.5),[moving,setMoving]=useState(false),[search,setSearch]=useState('');
 const requested=useSearchParams().get('contribution');
 const active=selected??(CONTRIBUTIONS.some(c=>c.id===requested)?requested!:'observatory');
 const item=CONTRIBUTIONS.find(c=>c.id===active)!,gap=compositionGap(a,b),ring=stationaryRing(moving?.8:.45);
 const papers=corpus.records.filter(r=>(r.title+' '+r.role).toLowerCase().includes(search.toLowerCase()));
 return <div className="discovery-page"><ObservatoryHeader/><main>
  <section className="discovery-hero"><div className="discovery-orbits" aria-hidden="true"><i/><i/><i/><b>∞</b></div><div className="discovery-hero-copy"><p className="discovery-label">THE READING ROOM / CONTRIBUTION LEDGER 001</p><h1>Boundaries.<br/>Connections.<br/><em>Possibilities.</em></h1><p className="discovery-intro">The Observatory is the instrument we are building: a map of what can be known, how things can change, and which discoveries let us see further.</p><a className="discovery-button" href="#contributions">Explore the discoveries ↓</a></div><div className="discovery-tally"><span><strong>41</strong> inventoried manuscripts</span><span><strong>11</strong> current in the audited corpus</span><span><strong>1</strong> connected research programme</span></div></section>
  <section className="discovery-section" id="engine"><p className="discovery-label">THE MATHEMATICAL SPINE</p><h2>A bound becomes useful when it constrains a question.</h2><p>Start with an observation. Name its limits. Specify the operation. Keep the history the task needs. Seek the test that exposes a missing distinction. Preserve the result and its dependencies so the next laboratory can begin further ahead.</p><div className="discovery-engine">{ENGINE_STAGES.map((s,i)=><a key={s.id} href={s.href}><small>0{i+1}</small><strong>{s.title}</strong><span>{s.question}</span></a>)}</div><p className="discovery-footnote">Existing manuscripts develop this architecture. Implementation is partial: the current site combines registered calculations, linked records and reviewed proposals. Automatic universal discovery is an objective, not an achieved capability.</p></section>
  <section className="discovery-section" id="contributions"><p className="discovery-label">DISCOVERIES, DEDUCTIONS & WORK WORTH KEEPING</p><h2>The ideas that build the instrument.</h2><p>Each contribution carries its conditions and its next use. A manuscript, an exact deduction, an implemented tool and an empirical discovery are different kinds of achievement.</p><div className="discovery-cabinet"><div className="discovery-tabs" role="tablist" aria-label="Contributions">{CONTRIBUTIONS.map((c,i)=><button key={c.id} role="tab" id={'tab-'+c.id} aria-selected={active===c.id} aria-controls="contribution-panel" tabIndex={active===c.id?0:-1} onKeyDown={e=>{const delta=e.key==='ArrowDown'||e.key==='ArrowRight'?1:e.key==='ArrowUp'||e.key==='ArrowLeft'?-1:0;if(delta){e.preventDefault();const next=CONTRIBUTIONS[(i+delta+CONTRIBUTIONS.length)%CONTRIBUTIONS.length];setActive(next.id);document.getElementById('tab-'+next.id)?.focus();}}} onClick={()=>setActive(c.id)}><small>FILE 0{i+1}</small>{c.title}<span>↗</span></button>)}</div><article id="contribution-panel" role="tabpanel" aria-labelledby={'tab-'+active} className="discovery-paper"><p className="discovery-label">{item.class}</p><h3>{item.title}</h3><p className="discovery-finding">{item.finding}</p><dl><dt>What it needs</dt><dd>{item.premises}</dd><dt>What it unlocks</dt><dd>{item.unlock}</dd><dt>Classical foundations</dt><dd>{item.ancestry}</dd><dt>What remains open</dt><dd>{item.limit}</dd></dl><div className="discovery-links"><a href={item.source}>Read the source ↗</a><a href={item.room}>Enter the laboratory →</a></div></article></div></section>
  <section className="discovery-section"><p className="discovery-label">TWO IDEAS YOU CAN TOUCH</p><h2>Same boundary. Different answers.</h2><div className="discovery-demos"><article><span className="discovery-label">01 / BOUNDED COMPOSITION</span><h3>Where do the mechanisms disagree?</h3><p>Compare Bliss independent action with Loewe dose equivalence for a common Hill slope of one. These are conditional models, not drug recommendations.</p><label>Effect A <output>{a.toFixed(3)}</output><input aria-label="Effect A" type="range" min="0.01" max="0.99" step="0.001" value={a} onChange={e=>setA(+e.target.value)}/></label><label>Effect B <output>{b.toFixed(3)}</output><input aria-label="Effect B" type="range" min="0.01" max="0.99" step="0.001" value={b} onChange={e=>setB(+e.target.value)}/></label><div className="discovery-meters" aria-live="polite"><div>Bliss <strong>{gap.bliss.toFixed(4)}</strong><meter min="0" max="1" value={gap.bliss}/></div><div>Loewe <strong>{gap.loewe.toFixed(4)}</strong><meter min="0" max="1" value={gap.loewe}/></div><p>Absolute gap <strong>{gap.gap.toFixed(5)}</strong></p></div><button onClick={()=>{setA((Math.sqrt(5)-1)/2);setB((Math.sqrt(5)-1)/2);}}>Show the exact maximum-gap point</button><details><summary>Equations & scope</summary><p>Bliss = a + b − ab. Loewe = (a + b − 2ab)/(1 − ab). The global maximum gap is (5√5 − 11)/2 ≈ 0.09017 at a = b = (√5 − 1)/2. Optimal statistical information also depends on noise and assay cost.</p><a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7426978">Bounded pharmacology manuscript ↗</a></details></article>
  <article><span className="discovery-label">02 / HIDDEN DYNAMICS</span><h3>The photograph misses the traffic.</h3><p>Three states can have equal long-run occupancy with or without a circulating probability current. Reveal time order to tell these examples apart.</p><div className={'discovery-ring '+(moving?'is-moving':'')} aria-label="Three states with equal one-third stationary probability"><span>A<small>⅓</small></span><b aria-hidden="true">{moving?'↻':'⇄'}</b><span>B<small>⅓</small></span><span>C<small>⅓</small></span></div><button onClick={()=>setMoving(!moving)}>{moving?'Restore reversible dynamics':'Reveal circulating dynamics'}</button><div aria-live="polite"><p>Clockwise probability: <strong>{moving?'0.80':'0.45'}</strong><br/>Counterclockwise: <strong>{moving?'0.10':'0.45'}</strong><br/>Net current per edge: <strong>{ring.current.toFixed(4)}</strong></p></div><details><summary>Model & inference boundary</summary><p>At each step the probability of staying is 0.10. Both transition matrices are doubly stochastic, so π = (⅓, ⅓, ⅓) is stationary. J = πᵢPᵢⱼ − πⱼPⱼᵢ. This exact three-state illustration is not a field measurement or evidence for a particular ecological mechanism.</p><a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=6963360">Niche–neutral manuscript ↗</a></details></article></div></section>
  <section className="discovery-section discovery-history"><p className="discovery-label">WHAT CAME BEFORE · WHAT THIS PROGRAMME ADDS</p><h2>Boundedness has a history.<br/>Its connections deserve a map.</h2><p>Finite ranges, saturation, geometric constraints and information limits already have deep scientific histories. The programme’s proposed contribution is to connect bounds to admissible operations, observation sufficiency and viable action in a reusable discovery instrument.</p><div className="discovery-history-links"><a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/j.1538-7305.1948.tb00917.x">1948 · Shannon<br/><span>Communication under finite capacity</span></a><a href="https://journals.aps.org/prd/abstract/10.1103/PhysRevD.23.287">1981 · Bekenstein<br/><span>A proposed entropy–energy bound</span></a><a href="https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/j.2517-6161.1982.tb01195.x">1982 · Aitchison<br/><span>Geometry of compositions</span></a><a href="https://arxiv.org/abs/1512.04666">2015/16 · Frenkel<br/><span>Einstein composition and its maps</span></a></div><p>A finite physical capacity, a bounded coordinate, an instrument ceiling and the largest value in a dataset are different objects. Mapping that difference is part of the work. A bounded observable alone does not select a geometry or prove universal boundedness.</p></section>
  <section className="discovery-section" id="frontiers"><p className="discovery-label">THE NEXT ROOM TO OPEN</p><h2>Information, agency & human wellbeing.</h2><p>A proposed investigation connects information load, processing capacity, predictability, social connection and wellbeing. First separate these quantities: mathematical entropy is not a direct measure of experienced overload.</p><div className="discovery-frontier"><h3>A question we can actually challenge</h3><p>Does information load relative to a measured capacity improve prediction of subsequent wellbeing beyond prior wellbeing, income, social connection and platform use?</p><ol><li>Define a population, measurement scales, timing and competing causal explanations.</li><li>Secure compatible longitudinal observations. Country averages alone cannot identify a personal mechanism.</li><li>Freeze a baseline and held-out test. Keep the capacity hypothesis only if it improves out-of-sample prediction with stable calibration and survives reverse-direction and missing-data checks.</li></ol><p><strong>Status: proposed protocol; no analysis run.</strong> Economic linearity, inevitable social collapse and a singularity mechanism are not established premises. The audited corpus does not yet supply a verified singularity-inversion manuscript or equation.</p><a href="https://www.worldhappiness.report/ed/2026/executive-summary-happiness-and-social-media/">Starting evidence: World Happiness Report 2026 ↗</a><p className="discovery-footnote">The report finds regional differences in youth wellbeing, not a uniform worldwide decline. This is a reason to compare explanations rather than assume the trend.</p></div></section>
  <section className="discovery-section" id="papers"><p className="discovery-label">THE SOURCE CABINET</p><h2>41 manuscripts. An evolving programme.</h2><p>The audited snapshot contains 11 current and 30 legacy records. These are not 41 independently validated discoveries. Current/legacy denotes programme lineage in that snapshot; public version parity remains unverified. Inspection notes preserve the extent of the existing review.</p><label className="discovery-search">Find a manuscript<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try composition, observer, action…"/></label><p aria-live="polite">{papers.length} records</p><p><a href="/api/discoveries">Read the shared machine-readable ledger ↗</a></p><div className="discovery-corpus">{papers.map(r=><details key={r.key}><summary><small>{r.corpus_kind}</small>{r.title}</summary><p>{r.role}</p><p><strong>Review extent:</strong> {r.inspection}. {r.assessment}</p><a href={'https://papers.ssrn.com/sol3/papers.cfm?abstract_id='+r.ssrn_id}>Open SSRN record ↗</a><p className="discovery-hash">Audited text SHA-256: {r.source_sha256}</p></details>)}</div></section>
 </main></div>;
}
