'use client';
/* oxlint-disable next/no-html-link-for-pages -- Stable case and device routes. */
import {useState} from 'react';
import {PAIRED_DAMAGE_CASE as c} from '@/lib/research-cases';
import {LEAD_MARGINS,replayPairedDamage} from '@/lib/paired-damage';
type Row=ReturnType<typeof replayPairedDamage>[number];
type Receipt={results:Row[];receiptSha256:string;inputs:{leadHours:number};[key:string]:unknown};
export default function CaseWorkbench({recorded,audit}:{recorded:Row[];audit:{sourceFigureRows:number;sourceRowsAtOrAfterEndpoint:number;excludedCensoredCells:number}}){
 const [margin,setMargin]=useState(7),[receipt,setReceipt]=useState<Receipt|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=receipt?.results??recorded,shownMargin=receipt?.inputs.leadHours??7;
 async function run(){setBusy(true);setError('');try{const response=await fetch(`/api/cases/${c.id}/replay`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({leadHours:margin})});const body=await response.json() as Receipt&{error?:string};if(!response.ok)throw new Error(body.error??'Replay failed');setReceipt(body);}catch(e){setError(e instanceof Error?e.message:'Replay failed');}finally{setBusy(false);}}
 function download(){if(!receipt)return;const url=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${c.id}-r${c.revision}-${shownMargin}h.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const point=(r:Row)=>`${60+(r.age-24.5)/49*640},${270-(r.fraction??0)*230}`;
 return <main className="case-workbench">
  <nav className="case-nav"><a href="/labs/biology">← Biological Surgery</a><a href="/question">Central computer</a><a href="#connections">Across the laboratories</a></nav>
  <header className="case-heading"><div><span className="case-eyebrow">BIOLOGY / SPECIMEN FILE {c.id} / REVISION {c.revision}</span><h1>When does damage<br/><em>give the future away?</em></h1><p>Two cells. A changing signal. One question about what we can know before the end.</p></div><div className="case-stamp">EXPLORATORY<br/>OBSERVATION<br/><small>Independent validation pending</small></div></header>
  <section className="case-result"><span className="case-eyebrow">WHAT SURVIVED THE AUDIT</span><p>{c.finding}</p><p>The contribution here is a reproducible question and comparison. The observed age dependence is consistent with the source paper’s broader account; novelty and a biological mechanism remain open.</p><a href={c.provenance.sourceArticle} target="_blank" rel="noreferrer">Read Yang et al. (2023) ↗</a></section>
  <section className="case-replay" aria-labelledby="replay-title"><div className="case-section-top"><div><span className="case-eyebrow">THE CHART RECORDER</span><h2 id="replay-title">Replay the evidence</h2></div><span className="case-status" role="status">{busy?'RECALCULATING':receipt?'REPLAY COMPLETE · 0 AI CALLS':'ARCHIVED RESULT · NOT YET REPLAYED'}</span></div>
   <p>Count pairs in which the lower PI-uptake value belongs to the cell with the later recorded death. Require both deaths to occur strictly beyond the selected margin. This margin tests sensitivity; selecting by future survival does not establish prospective prediction.</p>
   <div className="case-controls"><label htmlFor="lead-margin">Minimum time to either death<select id="lead-margin" value={margin} onChange={e=>setMargin(Number(e.target.value))} disabled={busy}>{LEAD_MARGINS.map(v=><option key={v} value={v}>{v} hours</option>)}</select></label><button onClick={run} disabled={busy}>{busy?'Replaying…':'Run recorded-data check'}</button><button onClick={()=>window.print()}>Print this report</button><button onClick={download} disabled={!receipt}>Export replay JSON</button></div>
   {error&&<p role="alert">{error}</p>}<p className="case-chart-caption">Displayed margin: <strong>{shownMargin} hours</strong>. {margin!==shownMargin?'Run the check to apply the changed setting.':''} Lines connect different eligible cohorts, not one fixed group.</p>
   <svg className="case-chart" viewBox="0 0 760 330" role="img" aria-labelledby="damage-chart-title damage-chart-desc"><title id="damage-chart-title">Fraction of pairs where lower damage accompanies later death</title><desc id="damage-chart-desc">Exact counts and exclusions for every plotted age follow in the table. The horizontal reference is fifty percent.</desc>{[0,.25,.5,.75,1].map(y=><g key={y}><line x1="60" x2="715" y1={270-y*230} y2={270-y*230} stroke={y===.5?'#cca969':'#30474b'} strokeDasharray={y===.5?'6 5':undefined}/><text x="48" y={275-y*230} textAnchor="end">{y*100}%</text></g>)}<polyline points={rows.filter(r=>r.fraction!==null).map(point).join(' ')} fill="none" stroke="#9de4d0" strokeWidth="3"/>{rows.map(r=><g key={r.age}>{r.fraction!==null&&<circle cx={60+(r.age-24.5)/49*640} cy={270-r.fraction*230} r="5" fill="#9de4d0"/>}<text x={60+(r.age-24.5)/49*640} y="298" textAnchor="middle">{r.age}</text></g>)}<text x="390" y="325" textAnchor="middle">Source measurement age (hours)</text></svg>
   <div className="case-table-wrap"><table><caption>Source-derived counts · both deaths observed · margin {shownMargin}h</caption><thead><tr><th>Age (h)</th><th>Correct direction</th><th>Fraction</th><th>Joined</th><th>Ties removed</th><th>Margin exclusions</th></tr></thead><tbody>{rows.map(r=><tr key={r.age}><td>{r.age}</td><td>{r.k} / {r.n}</td><td>{r.fraction===null?'No eligible pairs':`${(100*r.fraction).toFixed(1)}%`}</td><td>{r.joined}</td><td>{r.ties}</td><td>{r.excludedByLead}</td></tr>)}</tbody></table></div>
   <p>No p-value or probability of a theory being true is inferred. The same pairs can recur across ages. {audit.excludedCensoredCells} source cells are right-censored and excluded from the both-deaths cohort.</p>
   {receipt&&<div className="case-receipt"><strong>Replay receipt</strong><code>{receipt.receiptSha256}</code><p>The digest identifies this calculation record. It does not authenticate a scientific conclusion.</p></div>}
  </section>
  <section className="case-definitions"><div><span className="case-eyebrow">NOUNS / WHAT IS ACTUALLY OBSERVED</span><h2>Define the specimen</h2><dl>{c.nouns.map(n=><div key={n.name}><dt>{n.name}</dt><dd>{n.definition}</dd></div>)}</dl></div><div><span className="case-eyebrow">VERBS / WHAT THE CHECK DOES</span><h2>Keep the operations visible</h2><ol>{c.verbs.map(v=><li key={v}>{v}</li>)}</ol><p><strong>Executed:</strong> joining and counting archived observations.</p><p><strong>Not executed:</strong> a new biological experiment, fitted causal model or quantum calculation.</p></div></section>
  <section id="connections"><span className="case-eyebrow">ONE CASE / SHARED ACROSS THE OBSERVATORY</span><h2>What each laboratory receives</h2><p>Every room points to {c.id}, revision {c.revision}. Each connection states its own question and missing evidence. Biology remains the home of this record even if rooms are reorganised.</p><div className="case-connections">{c.connections.map(x=><article key={x.device}><small>{x.room.toUpperCase()} · {x.status}</small><h3>{x.role}</h3><p>{x.question}</p><ul>{x.requires.map(r=><li key={r}>{r}</li>)}</ul><a href={`/devices/${x.device}`}>Open the connected instrument →</a></article>)}</div></section>
  <section className="case-next"><span className="case-eyebrow">NEXT EXPERIMENT / {c.next.state}</span><h2>{c.next.title}</h2><p>{c.next.baseline}</p><h3>First clear the measurement gates</h3><ol>{c.next.readiness.map(r=><li key={r}>{r}</li>)}</ol><h3>Success and failure fixed in advance</h3><p>{c.next.success}</p><p>{c.next.failure}</p><p>{c.next.beforeFitting}</p><a href="/framework/work">Take this case to the research workshop →</a></section>
  <section className="case-audit"><span className="case-eyebrow">THE CORRECTION IS PART OF THE RESULT</span><h2>What this case cannot establish</h2><ul>{c.limits.map(l=><li key={l}>{l}</li>)}</ul>{c.corrections.map(r=><p key={r.revision}><strong>{r.revision} · {r.status}.</strong> {r.detail}</p>)}<p>The input figure contains {audit.sourceRowsAtOrAfterEndpoint} of {audit.sourceFigureRows} rows at or after a listed endpoint. Revision 2 enforces the explicit pair eligibility rule; this does not by itself imply that the source paper is wrong.</p></section>
  <footer className="case-sources"><h2>Follow every number back</h2><p>Source files are preserved byte-for-byte. Author attribution and definitions travel with the record.</p><div className="case-links"><a href={`/api/cases/${c.id}`}>Shared case JSON</a><a href={c.provenance.dataHref}>Paired observations + reference counts</a><a href="/research-cases/paired-damage/manifest.json">Provenance manifest</a><a href="/research-cases/paired-damage/reproduce.py">Reproduction script</a><a href="/encyclopedia#research-cases">Encyclopedia connection</a></div>{c.provenance.sourceFiles.map(s=><p key={s.file}><a href={s.href}>{s.file}</a><code>{s.sha256}</code></p>)}<p>Data digest <code>{c.provenance.dataSha256}</code></p><p>Software: <a href="/research-cases/paired-damage/paired-damage.ts.txt">replay calculation</a> · <a href="/research-cases/paired-damage/research-cases.ts.txt">case and branch contract</a></p></footer>
 </main>;
}
