'use client';
import { useEffect, useState } from 'react';
import type { Indicator } from '@/lib/world-bank';
type Catalogue = { indicators: Indicator[]; countries: { id: string; name: string }[]; catalogueSize: number; error?: string };
function SeriesSearch({ label, value, onSelect, disabled }: { label: string; value: Indicator | null; onSelect: (i: Indicator | null) => void; disabled: boolean }) {
  const [query, setQuery] = useState(''), [options, setOptions] = useState<Indicator[]>([]), [status, setStatus] = useState('Type a statistic to search the source catalogue.');
  useEffect(() => { if (query.trim().length < 2) return; const controller = new AbortController(); const timer = setTimeout(() => { setStatus('Searching the World Bank catalogue…'); void fetch(`/api/inquiry/data?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then(async r => { const body = await r.json() as Catalogue; if (!r.ok) throw new Error(body.error ?? 'Source unavailable'); setOptions(body.indicators); setStatus(`${body.indicators.length} matches shown from ${body.catalogueSize} indicators.`); }).catch(e => { if (!controller.signal.aborted) { setOptions([]); setStatus(e instanceof Error ? e.message : 'Search unavailable'); } }); }, 350); return () => { clearTimeout(timer); controller.abort(); }; }, [query]);
  return <div className="data-series"><label>{label}<input value={query} onChange={e => { setQuery(e.target.value); setOptions([]); onSelect(null); }} placeholder="e.g. life expectancy, unemployment, GDP" disabled={disabled} maxLength={100} /></label><small role="status">{status}</small>{options.length > 0 && <select aria-label={`${label} source definition`} value={value?.id ?? ''} onChange={e => onSelect(options.find(o => o.id === e.target.value) ?? null)} disabled={disabled}><option value="">Choose the exact definition</option>{options.map(i => <option key={i.id} value={i.id}>{i.name} · {i.id}</option>)}</select>}{value && <p>{value.sourceNote}</p>}</div>;
}
export default function DataExplorer({ onRun, busy }: { onRun: (prompt: string) => void; busy: boolean }) {
  const [x, setX] = useState<Indicator | null>(null), [y, setY] = useState<Indicator | null>(null), [country, setCountry] = useState('all'), [start, setStart] = useState('2023'), [end, setEnd] = useState('2023'), [countries, setCountries] = useState<Catalogue['countries']>([]), [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); void fetch('/api/inquiry/data?q=life%20expectancy', { signal: controller.signal }).then(async r => { const data = await r.json() as Catalogue; if (!r.ok) throw new Error(data.error ?? 'Could not retrieve countries.'); setCountries(data.countries); }).catch(e => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Source unavailable'); }); return () => controller.abort(); }, []);
  return <fieldset className="data-explorer" disabled={busy}><legend>Compare public statistics</legend><p>Search World Bank definitions, choose a common period, then retrieve the observations and test their association.</p><div className="data-search-grid"><SeriesSearch label="Statistic X" value={x} onSelect={setX} disabled={busy} /><SeriesSearch label="Statistic Y" value={y} onSelect={setY} disabled={busy} /></div><div className="data-period"><label>Compare<select value={country} onChange={e => setCountry(e.target.value)}><option value="all">Across countries and economies</option>{countries.map(c => <option key={c.id} value={c.id}>{c.name} over time</option>)}</select></label><label>{country === 'all' ? 'Observation year' : 'First year'}<input type="number" value={start} onChange={e => setStart(e.target.value)} min="1960" max={new Date().getFullYear()} /></label>{country !== 'all' && <label>Last year<input type="number" value={end} onChange={e => setEnd(e.target.value)} min={start} max={new Date().getFullYear()} /></label>}</div>{error && <p role="alert">{error}</p>}<button type="button" className="data-run" disabled={!x || !y || x.id === y.id || !start || (country !== 'all' && (!end || +end < +start))} onClick={() => { if (x && y) onRun(`Correlate World Bank ${x.id} with ${y.id}; country=${country}; years=${start}:${country === 'all' ? start : end}.`); }}>Fetch data → test association → print report</button></fieldset>;
}
