'use client';
/* oxlint-disable next/no-html-link-for-pages -- Native links share the stable application routes. */
import { useEffect, useState } from 'react';
import type { LabPrintout } from '@/lib/lab-contract';
type Entry = { id: string; title: string; question: string; scope: string; owner: string; status: string; source_version: string; evidence_class: string; source: { archive_sha256: string; file_sha256: string } };
export default function Encyclopedia({ entries }: { entries: Entry[] }) {
  const [run, setRun] = useState<LabPrintout | null>(null), [error, setError] = useState(''), [fragment, setFragment] = useState('');
  useEffect(() => { const hash = window.location.hash.slice(1), q = new URLSearchParams(hash), id = q.get('run'), token = q.get('key'); if (!id || !token) return;
    const abort = new AbortController();
    fetch(`/api/inquiry/${encodeURIComponent(id)}`, { headers: { Authorization: `Bearer ${token}` }, signal: abort.signal }).then(async response => { const body = await response.json() as { error?: string; printout: LabPrintout }; if (!response.ok) throw new Error(body.error ?? 'The saved inquiry is unavailable.'); return body.printout; }).then(value => { setRun(value); setFragment(hash); }).catch(e => { if (!abort.signal.aborted) setError(e instanceof Error ? e.message : 'Could not load inquiry.'); });
    return () => abort.abort();
  }, []);
  return <main className="cd-document"><nav><a href="/">← Central desk</a><a href="/agents">AI interface</a><a href="/projects">Projects</a></nav><span className="cd-label">RESEARCH LIBRARY · SOURCE-PINNED ENTRIES</span><h1>What follows.<br />What remains open.</h1><p>The encyclopedia separates a result from the conditions that make it true. Each entry retains its source, scope and unresolved decisions.</p>
    {error && <p role="alert">{error}</p>}{run && <section className="cd-inquiry-context"><span className="cd-label">YOUR SAVED INQUIRY · {run.id.slice(0, 8)}</span><h2>{run.summary}</h2><p>{run.prompt}</p><p>Receipt <code>{run.receiptSha256}</code></p><a href={`/question#${fragment}`}>Return to this exact printout →</a><p>This private record is read by this view. It does not change the admission status of a public entry.</p></section>}
    <div className="cd-entry-grid">{entries.map(entry => <article id={entry.id} key={entry.id}><span className="cd-label">{entry.id} · {entry.owner} · v{entry.source_version}</span><h2>{entry.title}</h2><h3>{entry.question}</h3><p>{entry.scope}</p><p><strong>Evidence:</strong> {entry.evidence_class}. <strong>Admission:</strong> {entry.status.replaceAll('_', ' ')}.</p>{run?.encyclopedia.filter(x => x.id === entry.id).map(link => <div className="cd-entry-link" key={link.id}><strong>Relationship to your inquiry</strong><p>{link.relationship}</p><small>{link.status}</small></div>)}<a href={`/labs/${entry.owner === 'encyclopedia' ? 'biology' : entry.owner}${fragment ? `#${fragment}` : ''}`}>Open the corresponding laboratory →</a><details><summary>Source identity and review</summary><p>Archive: <code>{entry.source.archive_sha256}</code></p><p>Entry: <code>{entry.source.file_sha256}</code></p><a href="https://github.com/thantiklermcirony/empirical-observatory/releases/tag/laboratory-sources-2026-09-12">Frozen source collection</a></details></article>)}</div>
    <section><h2>The next question is part of the result</h2><p>Corrections belong to a new inquiry revision, with the old record retained. A missing measurement becomes an explicit obligation. Source publication, executable testing and empirical support are separate decisions.</p><p>The current library is a finite set of reviewed and candidate research cases. It is not a complete encyclopedia of science, and no numerical “probability of truth” is fabricated for these entries.</p><a href="/research-index/entries.json">Download the entry index</a></section></main>;
}
