'use client';
/* oxlint-disable next/no-html-link-for-pages -- SIWC requires native top-level navigation. */
import {useState,useEffect,useCallback,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {ObservatoryHeader} from './LaboratoryIdentity';
import {FrameworkReceipt} from './ScienceFramework';
import type {FrameworkProposal} from '@/lib/framework-proposals';
export type ProposalRow={id:string;status:string;createdAt:string;updatedAt:string;prompt:string;proposal:FrameworkProposal|null;error:string|null};
export function ProposalView({row,editor=false,onAction}:{row:ProposalRow;editor?:boolean;onAction?:(action:string,id:string)=>void}){const p=row.proposal;return <article><span className="sf-kicker">{row.status==='candidate'?'PUBLISHED CANDIDATE · NOT ESTABLISHED':row.status.toUpperCase()} · {row.createdAt.slice(0,10)}</span><h2>{p?.draft.title??'Research instruction'}</h2><p>{row.prompt}</p>{row.error&&<p className="sf-error">{row.error}</p>}{p&&<><p>{p.draft.summary}</p><dl>{([['Proposed mechanism',p.draft.mechanism],['Competing explanation',p.draft.competingExplanation],['Prediction',p.draft.prediction],['Conventional baseline',p.draft.baseline],['Success criterion',p.draft.successCriterion],['Failure criterion',p.draft.failureCriterion]]).map(([k,v])=><div key={k}><dt><b>{k}</b></dt><dd>{v}</dd></div>)}</dl><details><summary>Observations, sources and implementation plan</summary><h3>Observables</h3><ul>{p.draft.observables.map(v=><li key={v}>{v}</li>)}</ul><h3>Still needed</h3><ul>{p.draft.missingEvidence.map(v=><li key={v}>{v}</li>)}</ul><h3>Build brief</h3><ul>{p.draft.implementationTasks.map(v=><li key={v}>{v}</li>)}</ul><h3>Sources consulted</h3>{p.sources.map(s=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.id} · {s.title} ↗</a><br/><small>{s.kind}</small></p>)}<p>Related claims: {p.draft.targetClaimIds.join(', ')||'New proposed area'}</p><p>Content receipt: <code>{p.receiptSha256}</code></p></details>{p.checks.map(c=><FrameworkReceipt key={c.id} receipt={c}/>)}<div className="sf-empty"><b>Review state: domain evidence still required</b><ul>{p.review.findings.map(f=><li key={f}>{f}</li>)}</ul></div><Button variant="outline" onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(row,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`observatory-proposal-${row.id}.json`;a.click();URL.revokeObjectURL(u);}}>Export proposal and checks</Button>{editor&&row.status==='draft'&&<Button onClick={()=>onAction?.('publish_candidate',row.id)}>Publish as an unvalidated candidate</Button>}{editor&&row.status==='candidate'&&<Button variant="outline" onClick={()=>onAction?.('retract',row.id)}>Retract candidate; retain history</Button>}</>}</article>}
export default function FrameworkWorkshop(){const[access,setAccess]=useState<{signedIn:boolean;editor:boolean;configured:boolean;setupId:string|null}|null>(null),[prompt,setPrompt]=useState('Extend the brain bioelectric record: identify the missing bridge from membrane current to scalp EEG, compare a conventional observation model, and propose the smallest useful test.'),[records,setRecords]=useState<ProposalRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<{id:string;prompt:string}|null>(null);
 const refresh=useCallback(async()=>{const a=await fetch('/api/framework/access').then(r=>r.json()) as {signedIn:boolean;editor:boolean;configured:boolean;setupId:string|null};setAccess(a);if(a.editor){const r=await fetch('/api/framework/proposals'),b=await r.json() as {error?:string;records:ProposalRow[]};if(!r.ok)throw new Error(b.error);setRecords(b.records);if(pending.current&&b.records.some(row=>row.id===pending.current!.id&&row.status!=='generating')){pending.current=null;localStorage.removeItem('observatory-framework-pending');}}},[]);
 // oxlint-disable-next-line react/react-compiler -- One asynchronous authentication fetch restores external browser draft state after hydration; no render-derived state loop.
 useEffect(()=>{void refresh().then(()=>{try{const saved=JSON.parse(localStorage.getItem('observatory-framework-pending')??'null');if(saved&&typeof saved.id==='string'&&typeof saved.prompt==='string'){pending.current=saved;setPrompt(saved.prompt);}}catch{}const q=new URLSearchParams(location.search);if(q.has('target'))setPrompt(`Propose the next mechanism record for anatomy ${q.get('target')}, system ${q.get('system')??'unmapped'}. Find primary evidence, state the competing explanation and required measurements, and give an implementation and test plan.`);}).catch(e=>setError(e.message));},[refresh]);
 const send=useCallback(async(action:string,id:string,instruction?:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/framework/proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,...(instruction?{prompt:instruction}:{})})});const b=await r.json() as {error?:string;record?:ProposalRow};if(!r.ok)throw new Error(b.error??'The workshop could not complete that instruction.');await refresh();return b;}catch(e){setError(e instanceof Error?e.message:'The workshop is unavailable.');try{await refresh();}catch{}throw e;}finally{setBusy(false);}},[refresh]);
 const propose=useCallback(async(instruction:string)=>{if(!pending.current||pending.current.prompt!==instruction){pending.current={id:crypto.randomUUID(),prompt:instruction};localStorage.setItem('observatory-framework-pending',JSON.stringify(pending.current));}return await send('propose',pending.current.id,instruction);},[send]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!access?.editor||!context?.registerTool)return;const lifecycle=new AbortController();const add=(tool:object)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};add({name:'observatory_framework_propose',description:'Create and save a candidate research proposal, consult primary sources, and run relevant registered model checks. Uses one call from the shared daily AI allowance. Does not publish or modify code.',inputSchema:{type:'object',properties:{prompt:{type:'string',maxLength:2000}},required:['prompt'],additionalProperties:false},execute:async({prompt:p}:{prompt:string})=>{setPrompt(p);return await propose(p);}});add({name:'observatory_framework_records',description:'Read editor research proposals and their saved test receipts.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>{const r=await fetch('/api/framework/proposals');return await r.json();}});return()=>lifecycle.abort();},[access?.editor,propose]);
 return <main className="science-framework"><ObservatoryHeader/><section className="sf-work"><span className="sf-kicker">INTERNAL RESEARCH / VERSIONED PROPOSALS</span><h1>Build the next connection.</h1><p>Ask for a mechanism, a test or an improvement to the framework. The AI seeks sources and writes a concrete proposal. Registered checks run in code; missing adapters remain explicit build tasks.</p><p><a href="/framework">← Physics and the living framework</a></p>{!access?<p>Checking editor access…</p>:!access.editor?<div className="sf-empty"><h2>Research workshop access</h2><p>{!access.signedIn?'Sign in with the Observatory owner or an approved editor account.':'This signed-in account is not configured as an Observatory editor.'}</p>{!access.signedIn&&<a href="/signin-with-chatgpt?return_to=%2Fframework%2Fwork" target="_top">Sign in with ChatGPT ↗</a>}{!access.configured&&access.setupId&&<details><summary>Owner setup identity</summary><p>Editor access is locked until the site owner configures this account on the server.</p><code data-editor-setup-id>{access.setupId}</code></details>}</div>:<><form onSubmit={e=>{e.preventDefault();void propose(prompt).catch(()=>{});}}><label htmlFor="framework-instruction">Research instruction</label><textarea id="framework-instruction" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={2000} disabled={busy}/><Button type="submit" disabled={busy||!prompt.trim()}>{busy?'Seeking sources and running available checks…':'Investigate and save proposal'}</Button><p className="sf-hint">One AI call per proposal, within the existing shared 200-call daily ceiling. Drafts are saved privately. After an interrupted request, submit the same instruction to recover its saved outcome; a new instruction starts a new proposal. Publishing makes the instruction, proposal, sources and checks public as an unvalidated candidate.</p></form><Button variant="outline" onClick={()=>void refresh().catch(e=>setError(e.message))} disabled={busy}>Refresh saved work</Button>{records.map(row=><ProposalView key={row.id} row={row} editor={!busy} onAction={(action,id)=>void send(action,id).catch(()=>{})}/>)}{!records.length&&<p>The next proposal starts the growth record.</p>}</>}{error&&<p className="sf-error" role="alert">{error}</p>}<p className="sf-hint">Proposals specify what to build. Source changes and deployment remain engineering operations; this page never executes generated code or upgrades a candidate into an established law.</p></section></main>;
}
