'use client';
/* oxlint-disable next/no-html-link-for-pages, next/no-img-element -- Native navigation and original scene assets. */
/* oxlint-disable react/react-compiler -- Room visibility synchronizes a native dialog and the pending camera transition; React Compiler is not enabled. */
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Monitor, Printer, FolderOpen, Volume2, VolumeX, X, Radio, Telescope } from 'lucide-react';
import {RoomDoors} from './ScienceRoom';
type Props = { active?:boolean; question?:string; busy:boolean; reportReady:boolean; enter:()=>void; openReport:()=>void; sound:boolean; toggleSound:()=>void; onQuestion?:(question:string)=>void };
export default function ObservatoryOffice({active=true,question,busy,reportReady,enter,openReport,sound,toggleSound}:Props) {
  const [panel,setPanel]=useState<'files'|'tv'|'uap'|null>(null);
  const [hint,setHint]=useState(''), [lights,setLights]=useState(true), [moving,setMoving]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null), arrival=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{if(panel)dialog.current?.showModal();else dialog.current?.close();},[panel]);
  useEffect(()=>()=>{if(arrival.current)clearTimeout(arrival.current);},[]);
  useEffect(()=>{if(!active){setPanel(null);setMoving(false);if(arrival.current)clearTimeout(arrival.current);}},[active]);
  function sit(){if(moving)return;setMoving(true);arrival.current=setTimeout(enter,window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:620);}
  const description=busy?(question ? 'Investigating: '+question : 'Your question is running. The report appears when the calculations return.'):reportReady?'Your report is on the printer. Take a look at what came back.':hint||'The computer is yours. The rest of the room is worth exploring.';
  return <>
    <section className={`office-scene ${lights?'':'office-lights-low'} ${moving?'office-entering':''}`} aria-label="Interactive observatory office">
      <div className="office-world"><img className="office-art" src="/images/office-night.webp" alt="The night office: a wooden desk, vintage computer, research folders and printer beneath a telescope dome." fetchPriority="high" /><div className="office-lighting" aria-hidden="true"/>
        <button className="office-hotspot office-terminal" onClick={sit} onMouseEnter={()=>setHint('CENTRAL COMPUTER · One question. Relevant laboratories. A traceable report.')} onMouseLeave={()=>setHint('')} aria-label="Sit at the computer terminal"><span className="office-mini-screen" aria-hidden="true"><small>EMPIRICAL / OS</small><span>{busy?'WORKING_':reportReady?'REPORT READY_':'ASK SOMETHING_'}</span><i>▌</i></span><span className="office-object-label"><Monitor size={16}/> Take the chair <kbd>01</kbd></span></button>
        <button className={`office-hotspot office-printer ${busy?'is-printing':''} ${reportReady?'has-report':''}`} onClick={openReport} disabled={!reportReady||busy} aria-label={busy?'Printer processing inquiry':reportReady?'Collect completed laboratory report':'Printer waiting for a question'}><span className="office-object-label"><Printer size={16}/>{busy?'Preparing your report':reportReady?'Collect your report':'The report printer'}</span>{(busy||reportReady)&&<span className="office-paper-ready" aria-hidden="true">EMPIRICAL OBSERVATORY<br/>{busy?'RECEIVING RESULTS…':'INQUIRY COMPLETE'}<br/>·····················<br/>{busy?'Please stand by.':'Ready to inspect.'}</span>}</button>
        <button className="office-hotspot office-file" onClick={()=>setPanel('files')} onMouseEnter={()=>setHint('THE OBSERVATORY · Open the room directory. Every instrument has a home.')} onMouseLeave={()=>setHint('')} aria-label="Open research files on the desk"><span className="office-file-crop" aria-hidden="true"/><span className="office-file-stamp" aria-hidden="true">EMPIRICAL<br/>RESEARCH DOSSIERS</span><span className="office-object-label"><FolderOpen size={16}/> Mathematics · Biology · Quantum <kbd>03</kbd></span></button>
        <button className="office-hotspot office-lamp" onClick={()=>setLights(!lights)} aria-pressed={!lights} aria-label="Dim the desk lighting"><span className="office-object-label">{lights?'A little more midnight':'Bring up the lights'}</span></button>
        <button className="office-hotspot office-poster" onClick={()=>setPanel('uap')} aria-label="E.T. poster: UAP research under construction"><span className="office-et-art" aria-hidden="true"/><span className="office-object-label">THE UNIDENTIFIED<br/><small>Under construction</small></span></button>
        <button className="office-hotspot office-tv" onClick={()=>setPanel('tv')} aria-label="Watch Carl Sagan archival broadcast with sound"><span className="office-tv-caption" aria-hidden="true">COSMOS<br/><small>TUNE IN</small></span><span className="office-object-label"><Radio size={16}/> A voice from the archives</span></button>
      </div>
      <span className="office-corner">EMPIRICAL OBSERVATORY<br/><span>FIELD STATION / 01</span></span>
      <div className={`office-status ${busy?'is-busy':''} ${reportReady?'is-ready':''}`} role="status"><span>{busy?<Printer size={18}/>:reportReady?<FolderOpen size={18}/>:<Telescope size={18}/>}</span><p>{description}</p>{reportReady&&!busy&&<button onClick={openReport}>Open report <ArrowUpRight size={16}/></button>}</div><span className="office-scene-caption">An imagined place for real questions.</span>
    </section>
    <nav className="office-controls" aria-label="Office controls"><span>THE NIGHT OFFICE</span><button onClick={sit}><Monitor size={16}/> Computer</button><button onClick={()=>setPanel('files')}><FolderOpen size={16}/> Laboratories</button><button disabled={!reportReady||busy} onClick={openReport}><Printer size={16}/> {busy?'Working…':reportReady?'Report ready':'Printer'}</button><button onClick={()=>setPanel('tv')}><Radio size={16}/> Sagan archive</button><button onClick={toggleSound} aria-pressed={sound} className="office-sound">{sound?<Volume2 size={16}/>:<VolumeX size={16}/>} Printer sound {sound?'on':'off'}</button></nav>
    <dialog className={`office-dialog office-dialog-${panel}`} ref={dialog} onCancel={()=>setPanel(null)} onClose={()=>setPanel(null)} aria-label={panel==='tv'?'Carl Sagan archive':panel==='uap'?'Unidentified phenomena dossier':'Research files'}><button className="office-dialog-close" aria-label="Close and return to office" onClick={()=>setPanel(null)}><X size={22}/></button>
      {panel==='files'&&<><span className="office-kicker">THE OBSERVATORY / ROOM DIRECTORY</span><h2>Choose a door.</h2><RoomDoors/><a className="catalogue-link" href="/catalogue">Every instrument, its source and its connections ↗</a></>}
      {panel==='tv'&&<><span className="office-kicker">THE ARCHIVE / CARL SAGAN</span><h2>“We are a way for the cosmos<br/>to know itself.”</h2><iframe title="Carl Sagan — We are a way for the Cosmos to know itself" src="https://www.youtube-nocookie.com/embed/rWnA4XLrMWA?autoplay=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><p>Original voice from <em>Cosmos</em>. The broadcast opens when you tune in. <a href="https://www.youtube.com/watch?v=rWnA4XLrMWA" target="_blank" rel="noreferrer">Watch on YouTube ↗</a></p></>}
      {panel==='uap'&&<><span className="office-kicker">CABINET X / UNIDENTIFIED PHENOMENA</span><h2>The sky still<br/><em>has questions.</em></h2><p className="office-uap-stamp">UNDER CONSTRUCTION</p><p>A place for unusual observations to receive an unusually careful examination.</p><div className="office-uap-list"><span>01 · Original sensor records</span><span>02 · Calibration & timing</span><span>03 · Competing explanations</span><span>04 · A test that tells them apart</span></div><p>No solved cases or extraterrestrial findings are claimed. The dossier is being prepared.</p><button className="office-enter" onClick={()=>{setPanel(null);enter();}}>Bring your question <ArrowUpRight size={18}/></button></>}
    </dialog>
  </>;
}
