'use client';
/* oxlint-disable next/no-html-link-for-pages, next/no-img-element -- Native navigation and original scene assets. */
/* oxlint-disable react/react-compiler -- Room visibility synchronizes a native dialog and the pending camera transition; React Compiler is not enabled. */
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, Monitor, Printer, FolderOpen, Volume2, VolumeX, X, Radio, Telescope } from 'lucide-react';
const files = [
  { id:'01', name:'Mathematics', subtitle:'The order of things', href:'/labs/mathematics', note:'Do the same two actions always lead to the same place?', kind:'Exact model', image:'precision' },
  { id:'02', name:'Biology', subtitle:'Recovery has a cost', href:'/labs/biology', note:'A signal recovers. Has the cell recovered with it?', kind:'Resource model', image:'life' },
  { id:'03', name:'Quantum', subtitle:'What measurement misses', href:'/labs/quantum', note:'Follow competing reaction pathways through a declared quantum model.', kind:'Quantum reference', image:'precision' },
  { id:'04', name:'Dynamics', subtitle:'The art of returning', href:'/labs/dynamics', note:'Disturb a system. Find out which controller actually brings it back.', kind:'Control simulation', image:'precision' },
  { id:'05', name:'Temporal grammar', subtitle:'Before. After. Because?', href:'/labs/temporal', note:'Keep the quantities, preparation and sequence that give a question meaning.', kind:'Inquiry method', image:'precision' },
  { id:'06', name:'Encyclopedia', subtitle:'The record stays open', href:'/encyclopedia', note:'Read the result, its conditions, and the observation that could change it.', kind:'Research library', image:'life' },
];
type Props = { active?:boolean; question?:string; busy:boolean; reportReady:boolean; enter:()=>void; openReport:()=>void; sound:boolean; toggleSound:()=>void; onQuestion?:(question:string)=>void };
export default function ObservatoryOffice({active=true,question,busy,reportReady,enter,openReport,sound,toggleSound,onQuestion}:Props) {
  const [panel,setPanel]=useState<'files'|'tv'|'uap'|null>(null);
  const [hint,setHint]=useState(''), [lights,setLights]=useState(true), [moving,setMoving]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null), arrival=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>{if(panel)dialog.current?.showModal();else dialog.current?.close();},[panel]);
  useEffect(()=>()=>{if(arrival.current)clearTimeout(arrival.current);},[]);
  useEffect(()=>{if(!active){setPanel(null);setMoving(false);if(arrival.current)clearTimeout(arrival.current);}},[active]);
  function sit(){if(moving)return;setMoving(true);arrival.current=setTimeout(enter,window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:620);}
  const description=busy?(question ? 'Investigating: '+question : 'Your question is running. The report appears when the calculations return.'):reportReady?'Your report is on the printer. Take a look at what came back.':hint||'The computer is yours. The rest of the room is worth exploring.';
  return <>
    <section className={`office-scene ${lights?'':'office-lights-low'} ${moving?'office-entering':''}`} aria-label="Interactive observatory office">
      <div className="office-world"><img className="office-art" src="/images/office-night.webp" alt="The night office: a wooden desk, vintage computer, research folders and printer beneath a telescope dome." fetchPriority="high" /><div className="office-lighting" aria-hidden="true"/>
        <button className="office-hotspot office-terminal" onClick={sit} onMouseEnter={()=>setHint('CENTRAL COMPUTER · One question. Relevant laboratories. A traceable report.')} onMouseLeave={()=>setHint('')} aria-label="Sit at the computer terminal"><span className="office-mini-screen" aria-hidden="true"><small>EMPIRICAL / OS</small><span>{busy?'WORKING_':reportReady?'REPORT READY_':'ASK SOMETHING_'}</span><i>▌</i></span><span className="office-object-label"><Monitor size={16}/> Take the chair <kbd>01</kbd></span></button>
        <button className={`office-hotspot office-printer ${busy?'is-printing':''} ${reportReady?'has-report':''}`} onClick={openReport} disabled={!reportReady||busy} aria-label={busy?'Printer processing inquiry':reportReady?'Collect completed laboratory report':'Printer waiting for a question'}><span className="office-object-label"><Printer size={16}/>{busy?'Preparing your report':reportReady?'Collect your report':'The report printer'}</span>{(busy||reportReady)&&<span className="office-paper-ready" aria-hidden="true">EMPIRICAL OBSERVATORY<br/>{busy?'RECEIVING RESULTS…':'INQUIRY COMPLETE'}<br/>·····················<br/>{busy?'Please stand by.':'Ready to inspect.'}</span>}</button>
        <button className="office-hotspot office-file" onClick={()=>setPanel('files')} onMouseEnter={()=>setHint('RESEARCH DOSSIERS · Six branches. Start with the question that bothers you.')} onMouseLeave={()=>setHint('')} aria-label="Open research files on the desk"><span className="office-file-crop" aria-hidden="true"/><span className="office-file-stamp" aria-hidden="true">EMPIRICAL<br/>RESEARCH DOSSIERS</span><span className="office-object-label"><FolderOpen size={16}/> Mathematics · Biology · Quantum <kbd>03</kbd></span></button>
        <button className="office-hotspot office-lamp" onClick={()=>setLights(!lights)} aria-pressed={!lights} aria-label="Dim the desk lighting"><span className="office-object-label">{lights?'A little more midnight':'Bring up the lights'}</span></button>
        <button className="office-hotspot office-poster" onClick={()=>setPanel('uap')} aria-label="E.T. poster: UAP research under construction"><span className="office-et-art" aria-hidden="true"/><span className="office-object-label">THE UNIDENTIFIED<br/><small>Under construction</small></span></button>
        <button className="office-hotspot office-tv" onClick={()=>setPanel('tv')} aria-label="Watch Carl Sagan archival broadcast with sound"><span className="office-tv-caption" aria-hidden="true">COSMOS<br/><small>TUNE IN</small></span><span className="office-object-label"><Radio size={16}/> A voice from the archives</span></button>
      </div>
      <div className="office-caption"><span className="office-kicker"><i/> THE NIGHT SHIFT IS OPEN</span><h1>A universe of questions.<br/><em>A desk to begin.</em></h1><p>Ask something. Test what follows.<br/>Find the next piece of the picture.</p><button className="office-enter" onClick={sit}>Take the chair <ArrowUpRight size={19}/></button><a href="#research-files" className="office-explore">Explore the laboratories <ArrowDown size={15}/></a></div>
      <span className="office-corner">EMPIRICAL OBSERVATORY<br/><span>FIELD STATION / 01</span></span>
      <div className={`office-status ${busy?'is-busy':''} ${reportReady?'is-ready':''}`} role="status"><span>{busy?<Printer size={18}/>:reportReady?<FolderOpen size={18}/>:<Telescope size={18}/>}</span><p>{description}</p>{reportReady&&!busy&&<button onClick={openReport}>Open report <ArrowUpRight size={16}/></button>}</div><span className="office-scene-caption">An imagined place for real questions.</span>
    </section>
    <nav className="office-controls" aria-label="Office controls"><span>ON YOUR DESK</span><button onClick={sit}><Monitor size={16}/> Computer</button><button onClick={()=>setPanel('files')}><FolderOpen size={16}/> Dossiers</button><button disabled={!reportReady||busy} onClick={openReport}><Printer size={16}/> {busy?'Working…':reportReady?'Report ready':'Printer'}</button><button onClick={()=>setPanel('tv')}><Radio size={16}/> Sagan archive</button><button onClick={toggleSound} aria-pressed={sound} className="office-sound">{sound?<Volume2 size={16}/>:<VolumeX size={16}/>} Printer sound {sound?'on':'off'}</button></nav>
    <section className="office-discover" id="research-files" aria-labelledby="research-files-title"><div className="office-section-intro"><div><span className="office-kicker">FOLLOW A THREAD</span><h2 id="research-files-title">Which question<br/><em>will keep you here?</em></h2></div><p>The same observatory. Different ways of looking.<br/>Choose a laboratory and put an idea to work.</p></div><div className="office-projects">{files.map(file=><a className={`office-dossier dossier-${file.image}`} href={file.href} aria-label={file.name} key={file.id}><div className="office-dossier-image"><span>LABORATORY / {file.id}</span><span className="office-dossier-tag">{file.kind}</span></div><div className="office-dossier-body"><span className="office-file-name">{file.name}<ArrowUpRight size={19}/></span><h3>{file.subtitle}</h3><p>{file.note}</p></div></a>)}</div><a className="office-all-labs" href="/#deck">The experiment floor · all workbenches <ArrowUpRight size={18}/></a></section>
    <section className="office-question-strip"><div>Not sure where to begin?</div><button onClick={()=>onQuestion?onQuestion('Is GDP per capita (current US$) correlated with life expectancy at birth across countries in 2023?'):enter()}>Does greater wealth go with a longer life? <ArrowUpRight size={18}/></button><button onClick={()=>onQuestion?onQuestion('Compare alignment then contraction with contraction then alignment in the declared bounded scalar model. x=1/4, u=1/3, c=1/2.'):enter()}>Can changing the order change the result? <ArrowUpRight size={18}/></button></section>
    <footer className="office-footer"><span>Curiosity is the beginning. Evidence is the way forward.</span><a href="/projects">All projects ↗</a><a href="https://github.com/thantiklermcirony/empirical-observatory" target="_blank" rel="noreferrer">Open source ↗</a></footer>
    <dialog className={`office-dialog office-dialog-${panel}`} ref={dialog} onCancel={()=>setPanel(null)} onClose={()=>setPanel(null)} aria-label={panel==='tv'?'Carl Sagan archive':panel==='uap'?'Unidentified phenomena dossier':'Research files'}><button className="office-dialog-close" aria-label="Close and return to office" onClick={()=>setPanel(null)}><X size={22}/></button>
      {panel==='files'&&<><span className="office-kicker">FROM THE CHIEF ENGINEER&apos;S DESK</span><h2>Pick up a thread.</h2><div className="office-file-index">{files.map(file=><a href={file.href} aria-label={file.name} key={file.id}><span>{file.id}</span><div><h3>{file.name}</h3><p>{file.note}</p></div><ArrowUpRight size={20}/></a>)}</div><a href="/projects">The complete project cabinet ↗</a></>}
      {panel==='tv'&&<><span className="office-kicker">THE ARCHIVE / CARL SAGAN</span><h2>“We are a way for the cosmos<br/>to know itself.”</h2><iframe title="Carl Sagan — We are a way for the Cosmos to know itself" src="https://www.youtube-nocookie.com/embed/rWnA4XLrMWA?autoplay=1&rel=0" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><p>Original voice from <em>Cosmos</em>. The broadcast opens when you tune in. <a href="https://www.youtube.com/watch?v=rWnA4XLrMWA" target="_blank" rel="noreferrer">Watch on YouTube ↗</a></p></>}
      {panel==='uap'&&<><span className="office-kicker">CABINET X / UNIDENTIFIED PHENOMENA</span><h2>The sky still<br/><em>has questions.</em></h2><p className="office-uap-stamp">UNDER CONSTRUCTION</p><p>A place for unusual observations to receive an unusually careful examination.</p><div className="office-uap-list"><span>01 · Original sensor records</span><span>02 · Calibration & timing</span><span>03 · Competing explanations</span><span>04 · A test that tells them apart</span></div><p>No solved cases or extraterrestrial findings are claimed. The dossier is being prepared.</p><button className="office-enter" onClick={()=>{setPanel(null);enter();}}>Bring your question <ArrowUpRight size={18}/></button></>}
    </dialog>
  </>;
}
