'use client';
/* oxlint-disable next/no-html-link-for-pages -- Stable native routes work in the published runtime. */
import {useEffect,useRef,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {CASE_EXPERIMENTS,CHLAM_STATE_LEDGER,type CaseRequest,type CaseRun} from '@/lib/case-engine-contract';
import './research-case-engine.css';

function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Vessel({count=1,label}:{count?:number;label:string}){return <div className="rce-vessel"><svg viewBox="0 0 360 205" role="img" aria-label={label}><defs><radialGradient id="culture"><stop stopColor="#224332"/><stop offset="1" stopColor="#080f12"/></radialGradient></defs><ellipse cx="180" cy="100" rx="164" ry="91" fill="url(#culture)" stroke="#56715d"/>{Array.from({length:Math.min(32,count)},(_,i)=>{const n=Math.min(count,32),angle=i*2.39996,r=n===1?0:Math.sqrt((i+.5)/n)*74,x=180+Math.cos(angle)*r*1.55,y=100+Math.sin(angle)*r;return <g key={i} transform={`translate(${x} ${y})`}><ellipse rx={count===1?32:12} ry={count===1?42:16} fill="#88b762" fillOpacity=".65" stroke="#d5e6a6"/><ellipse cy="2" rx={count===1?20:7} ry={count===1?28:10} fill="#2f603d"/><circle cx="4" cy="-4" r={count===1?5:2} fill="#dda774"/></g>;})}<path d="M24 180h55m-55-4v8m55-8v8" stroke="#c4d3a7"/><text x="89" y="184" fill="#9eb29b" fontSize="10">MODEL VIEW · NO PHYSICAL SCALE</text></svg><span>{label}{count>32?' · 32 symbols shown':''}</span></div>;}
function TracePlot({run,field,label}:{run:CaseRun;field:'totalVolume'|'descendants'|'regulator';label:string}){
 const a=run.runs[0],b=run.runs[1];if(!a)return null;
 // Every trajectory has regular five-minute sampling, plus a possible final sample.
 const points=a.trace.map((v,i)=>({hours:v.minutes/60,A:v[field],B:b?.trace[i]?.minutes===v.minutes?b.trace[i][field]:null}));
 return <figure className="rce-chart"><figcaption>{label}<small>5-minute samples · event times retained in the report</small></figcaption><div style={{width:'100%',height:210}}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{top:10,left:0,right:14,bottom:5}}><CartesianGrid stroke="#ffffff0d"/><XAxis dataKey="hours" type="number" domain={['dataMin','dataMax']} tick={{fill:'#a7b2b3',fontSize:11}} label={{value:run.request.experiment==='state'?'Hours after checkpoint':'Hours',position:'insideBottomRight',offset:-2,fill:'#a7b2b3'}}/><YAxis width={45} tick={{fill:'#a7b2b3',fontSize:11}}/><Tooltip contentStyle={{background:'#112127',borderColor:'#506267',color:'#eff3e7'}} formatter={value=>typeof value==='number'?Number(value.toPrecision(6)):value}/><Line name="A" dataKey="A" stroke="#cfdf9c" dot={false} isAnimationActive={false} type={field==='descendants'?'stepAfter':'linear'} strokeWidth={2}/><Line name="B" dataKey="B" stroke="#e0a980" dot={false} isAnimationActive={false} type={field==='descendants'?'stepAfter':'linear'} strokeWidth={2}/></LineChart></ResponsiveContainer></div></figure>;
}
export default function ResearchCaseEngine(){
 const [request,setRequest]=useState<CaseRequest>({experiment:'state',hours:48,slots:6}),[run,setRun]=useState<CaseRun|null>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState('Ready for an experiment.'),[error,setError]=useState('');
 const worker=useRef<Worker|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),serial=useRef(0),file=useRef<HTMLInputElement>(null);
 const [frame,setFrame]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing||!run?.runs[0])return;const last=run.runs[0].trace.length-1;if(frame>=last)return;const tick=setTimeout(()=>setFrame(i=>Math.min(last,i+6)),120);return()=>clearTimeout(tick);},[playing,run,frame]);
 const printReport=()=>{setPlaying(false);const collapsed=Array.from(document.querySelectorAll<HTMLDetailsElement>('.rce details:not([open])'));collapsed.forEach(d=>d.open=true);const restore=()=>{collapsed.forEach(d=>d.open=false);window.removeEventListener('afterprint',restore);};window.addEventListener('afterprint',restore);window.print();};
 const lastFrame=run?.runs[0]?.trace.length?run.runs[0].trace.length-1:0;
 const stop=()=>{serial.current++;worker.current?.terminate();worker.current=null;if(timeout.current)clearTimeout(timeout.current);timeout.current=null;};
 useEffect(()=>()=>{worker.current?.terminate();if(timeout.current)clearTimeout(timeout.current);},[]);
 const change=(value:CaseRequest)=>{stop();setPlaying(false);setBusy(false);setRun(null);setError('');setProgress('Configuration changed. Run to calculate fresh evidence.');setRequest(value);};
 const execute=()=>{stop();setPlaying(false);setRun(null);setError('');setBusy(true);setProgress('Starting an isolated numerical worker…');const id=serial.current;
  try{const w=new Worker('/research-cases/runtime/chlamydomonas-worker.mjs',{type:'module'});worker.current=w;
   const fail=(message:string)=>{if(serial.current!==id)return;stop();setBusy(false);setError(message);setProgress('Run failed. No result admitted.');};
   w.onerror=()=>fail('The case worker could not load or execute. Check the connection and retry.');
   w.onmessage=(event:MessageEvent<{type:string;message?:string;result?:CaseRun}>)=>{if(serial.current!==id)return;if(event.data.type==='progress'){setProgress(event.data.message??'Calculating…');return;}if(event.data.type==='error'){fail(event.data.message??'Execution failed.');return;}if(event.data.type==='result'&&event.data.result){setRun(event.data.result);setFrame((event.data.result.runs[0]?.trace.length??1)-1);setBusy(false);setProgress('Run complete. Inspect every gate below.');stop();}};
   timeout.current=setTimeout(()=>fail('The two-minute browser execution budget was reached. Try the 20-history grid or use the downloadable source locally.'),120000);w.postMessage(request);
  }catch(e){stop();setBusy(false);setError(e instanceof Error?e.message:'Could not start the worker.');}
 };
 const importConfig=async(f:File)=>{try{if(f.size>16000)throw Error('Configuration is too large.');const v=JSON.parse(await f.text());if(v.schema!=='observatory-case-config/1'||Object.keys(v).some(k=>!['schema','request'].includes(k)))throw Error('Import a saved configuration, not a result report.');const r=v.request;if(!r||Object.keys(r).sort().join(',')!=='experiment,hours,slots'||!CASE_EXPERIMENTS.some(e=>e.id===r.experiment)||![48,96].includes(r.hours)||![6,8].includes(r.slots)||(r.experiment!=='timing'&&r.hours!==48)||(r.experiment!=='state'&&r.slots!==6))throw Error('Invalid or unsupported configuration.');change(r);}catch(e){setError(e instanceof Error?e.message:'Invalid configuration.');}};
 const experiment=CASE_EXPERIMENTS.find(e=>e.id===request.experiment)!;
 return <main className="rce"><nav className="rce-nav"><a href="/">← Observatory</a><a href="/labs/biology">Biology room</a><a href="/cases">Case archive</a><a href="/ledger">Scientific ledger</a></nav>
  <header className="rce-header"><div><span className="rce-eyebrow">BIO–CHLAM–001 / RESEARCH CASE ENGINE</span><h1>What does a cell<br/><em>need to remember?</em></h1><p>A living model. An explicit state. An experiment that must survive its own checks.</p></div><div className="rce-stamp">HELDT MODEL / 8 STATES<br/>LOCAL COMPUTATION<br/><strong>No AI calls required</strong></div></header>
  <div className="rce-flow" aria-label="Case execution schematic">{['State ledger','Input histories','Equal-observation pairs','Candidate dials','Stress checks','Evidence record'].map((s,i)=><span key={s}><small>0{i+1}</small>{s}</span>)}</div>
  <div className="rce-console"><aside className="rce-controls"><span className="rce-eyebrow">CHOOSE AN INVESTIGATION</span><div role="group" aria-label="Experiments">{CASE_EXPERIMENTS.map(e=><button key={e.id} className={'rce-preset '+(e.id===request.experiment?'selected':'')} aria-pressed={e.id===request.experiment} onClick={()=>change({experiment:e.id,hours:48,slots:6})}><span>{e.number}</span><div><strong>{e.title}</strong><small>{e.description}</small></div></button>)}</div>
    {request.experiment==='state'&&<label className="rce-select">History grid<select value={request.slots} onChange={e=>change({...request,slots:Number(e.target.value) as 6|8})}><option value="6">20 histories · 6 four-hour slots</option><option value="8">70 histories · 8 three-hour slots</option></select><small>Half the slots lit. 24-hour preparation, then the same 24-hour dark future. The 70-history extension is exploratory.</small></label>}
    {request.experiment==='timing'&&<label className="rce-select">Observation endpoint<select value={request.hours} onChange={e=>change({...request,hours:Number(e.target.value) as 48|96})}><option value="48">48 hours · original contrast</option><option value="96">96 hours · test delay versus arrest</option></select></label>}
    <button className="rce-run" disabled={busy} onClick={execute}>{busy?'Calculating…':experiment.label}<span>↗</span></button>{busy&&<button className="rce-cancel" onClick={()=>{stop();setBusy(false);setProgress('Cancelled. No partial result retained.');}}>Cancel run</button>}
    <p className="rce-progress" role="status" aria-live="polite">{progress}</p>{error&&<p className="rce-error" role="alert">{error}</p>}
    <div className="rce-config-actions"><button onClick={()=>download({schema:'observatory-case-config/1',request},'chlamydomonas-configuration.json')}>Save setup</button><button onClick={()=>file.current?.click()}>Load setup</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importConfig(f);e.target.value='';}}/></div>
    <a className="rce-source-link" href="/research-cases/chlamydomonas/Chlamydomonas_Observatory.html">Open the full 27-dial sandbox ↗</a><small className="rce-muted">The standalone sandbox retains its own exploratory controls. It does not automatically run this engine’s gates.</small>
   </aside><section className="rce-workspace" aria-label="Experiment results">
    {!run?<div className="rce-idle"><span className="rce-eyebrow">SPECIMEN 001 / CHLAMYDOMONAS MODEL</span><Vessel label="Illustrative cell model · awaiting execution"/><h2>{experiment.title}</h2><p>{experiment.description}</p><div className="rce-note"><strong>The protocol is declared before you run.</strong><p>{request.experiment==='state'?'Match volume, generation and accumulated light at the checkpoint. Forecast any division in the next 24 hours. Compare volume, time since light ended, and one internal regulator chosen on development histories. Refine the selected witness and check the registered independent reference.':request.experiment==='empirical'?'Replay frozen out-of-experiment predictions. Compare the baseline and added-history Brier scores on all 3,679 records. A worse pooled score rejects the claimed descriptive benefit. No refitting occurs.':'Compare the same declared configurations at finer steps, preserve event counts and times, and check the pinned independent BDF reference. Numerical success remains conditional on the model.'}</p></div></div>:<>
      <div className="rce-result-heading"><span className="rce-eyebrow">EXECUTED / {run.evidenceClass.replaceAll('-',' ')}</span><h2>{run.classification.replaceAll('-',' ')}</h2><p>{run.finding}</p><p className="rce-muted">{run.caseId} · {new Date(run.createdAt).toISOString()} · {run.engineVersion}</p><div className="rce-result-actions"><button onClick={()=>download(run,`BIO-CHLAM-001-${run.request.experiment}-${run.receiptSha256.slice(0,10)}.json`)}>Export complete record ↓</button><button onClick={printReport}>Print report</button></div></div>
      {run.runs.length>0&&<><div className="rce-playback"><button onClick={()=>{if(playing&&frame<lastFrame)setPlaying(false);else{setFrame(0);setPlaying(true);}}}>{playing&&frame<lastFrame?'Pause':'Play the computed history'}</button><label>Observation time · {((run.runs[0].trace[frame]?.minutes??0)/60).toFixed(2)} h<input aria-label="Observation time" type="range" min="0" max={lastFrame} value={frame} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/></label><small>Vessels show sampled counts at the selected time; exact event times remain in the report.</small></div><div className="rce-pair">{run.runs.map((r,i)=>{const snapshot=r.trace[Math.min(frame,r.trace.length-1)];return <article key={r.label}><span className="rce-eyebrow">{i?'B / CANDIDATE':'A / COMPARATOR'}</span><Vessel count={snapshot.descendants} label={`${snapshot.descendants} represented descendant${snapshot.descendants===1?'':'s'}`}/><h3>{r.label}</h3><dl><div><dt>Lineage volume now</dt><dd>{snapshot.totalVolume.toFixed(6)} AV</dd></div><div><dt>Cell volume now</dt><dd>{snapshot.volume.toFixed(6)} AV</dd></div><div><dt>First division in full run</dt><dd>{r.firstDivisionMinutes===null?'Not within this horizon':(r.firstDivisionMinutes/60).toFixed(4)+' h'}</dd></div></dl></article>;})}</div><TracePlot run={run} field="totalVolume" label="Accumulated lineage volume · AV"/><TracePlot run={run} field="descendants" label="Represented descendants · count"/>{run.request.experiment==='state'&&<TracePlot run={run} field="regulator" label="Light-responsive regulator SK/V · AU/AV"/>}</>}
      {run.details.overall&&<section className="rce-table-section"><h3>Held-out prediction replay</h3><p>{run.details.method}</p><table><thead><tr><th>Experiment</th><th>Cells</th><th>Size + time Brier</th><th>+ History Brier</th></tr></thead><tbody>{run.details.folds?.map(f=><tr key={f.hours}><th>{f.hours} h</th><td>{f.n}</td><td>{f.baseline.toFixed(6)}</td><td>{f.candidate.toFixed(6)}</td></tr>)}<tr><th>Pooled</th><td>{run.details.overall.n}</td><td>{run.details.overall.baseline.toFixed(6)}</td><td>{run.details.overall.candidate.toFixed(6)}</td></tr></tbody></table><p>{run.details.uncertainty}</p></section>}
      {run.details.levels&&<section className="rce-table-section"><h3>A numerical illusion, tested</h3><table><thead><tr><th>Step · min</th><th>First-division difference · min</th></tr></thead><tbody>{run.details.levels.map(l=><tr key={l.dtMinutes}><td>{l.dtMinutes}</td><td>{l.differenceMinutes.toFixed(6)}</td></tr>)}</tbody></table></section>}
      {run.details.candidates&&<section className="rce-table-section"><h3>Does the hidden dial beat a simpler explanation?</h3><p>{run.details.search?.split}</p><table><thead><tr><th>Predictor</th><th>Development Brier</th><th>Held-out Brier</th></tr></thead><tbody>{run.details.candidates.map(c=><tr key={c.feature}><th>{c.feature}</th><td>{c.trainingBrier.toFixed(6)}</td><td>{c.testBrier.toFixed(6)} · n={c.testN}</td></tr>)}</tbody></table><p>{run.details.search?.predictor}</p><p>{run.details.search?.limits}</p></section>}
      <section className="rce-gates"><h3>Evidence gates</h3>{run.gates.map(g=><article key={g.id} className={'rce-gate '+g.status}><span>{g.status==='pass'?'PASS':g.status==='fail'?'FAIL':'OPEN'}</span><div><strong>{g.label}</strong><p>{g.detail}</p></div></article>)}</section>
      {run.details.rows&&<details className="rce-table-section"><summary>All {run.details.rows.length} searched histories and their outcomes</summary><p>Read bits from left to right: 1 = light, 0 = dark. A missing event time is censored by the horizon.</p><div className="rce-scroll"><table><thead><tr><th>History</th><th>Partition</th><th>Checkpoint V</th><th>Future descendants</th><th>First division · min</th></tr></thead><tbody>{run.details.rows.map(r=><tr key={r.history}><th>{r.history}</th><td>{r.split}</td><td>{r.checkpointState[0].toFixed(6)}</td><td>{r.descendantsDuringFuture}</td><td>{r.firstDivisionMinutes===null?'Not observed':r.firstDivisionMinutes.toFixed(4)}</td></tr>)}</tbody></table></div></details>}
      <details className="rce-provenance"><summary>Assumptions, state vectors and receipt</summary><ul>{run.limitations.map(l=><li key={l}>{l}</li>)}</ul><p>{run.ai.role}</p>{run.runs.map(r=><p key={r.label}><strong>{r.label} · final state [V, SK, TF, IN, INTF, IP, S, M]</strong><br/><code>{r.state.map(v=>v.toPrecision(7)).join(', ')}</code></p>)}<p>Source commit <code>{run.provenance.sourceCommit}</code></p><p>Run SHA-256 <code>{run.receiptSha256}</code></p><p>A content hash detects changes. It is not proof, authentication or a scientific truth score. The exported JSON contains configurations, gates, traces, source hashes and the adapter identity.</p><a href="/research-cases/runtime/case-core.mjs">Receipt verification source ↗</a></details>
     </>}
   </section></div>
  <section className="rce-ledger"><div><span className="rce-eyebrow">THE SHARED CONTRACT</span><h2>Nouns. Verbs. Dials. Boundaries.</h2><p>The model can connect to another lab only through a defined quantity and an admissible transformation. A shared word is not a connector.</p></div><div className="rce-scroll"><table><thead><tr><th>Noun / observable</th><th>Unit & bound</th><th>Verb / equation</th></tr></thead><tbody>{CHLAM_STATE_LEDGER.map(r=><tr key={r.noun}><th>{r.noun}</th><td><strong>{r.unit}</strong><br/>{r.bound}</td><td>{r.verb}<small>{r.equation}</small></td></tr>)}</tbody></table></div></section>
  <section className="rce-next"><span className="rce-eyebrow">NEXT EXPERIMENT / BEFORE NEW FITTING</span><h2>Can a measured state beat timing alone?</h2><p>Record light history, calibrated size, a measurable regulator proxy and subsequent division in independent lineages. Compare size + elapsed darkness against the same model with the regulator added. Choose the observation time, 24-hour outcome, censoring rule, assay and independent experiment split before fitting.</p><p><strong>Proposed success gate:</strong> at least 5% lower held-out Brier score, an experiment-cluster 95% interval for improvement entirely above zero, and calibration slope 0.8–1.2. An evaluable miss rejects the proposed advantage; missing calibration or too few independent experiments leaves it unresolved. Passing would support prediction in that protocol, not a universal law.</p><p>The immediate software result is a reusable case protocol. Energy, redox, radiation and quantum links remain explicit proposed adapters until their units, mechanisms and tests exist.</p><div><a href="/api/cases/BIO-CHLAM-001">Machine-readable case</a><a href="/encyclopedia#research-cases">Encyclopedia connection</a><a href="/labs/mathematics">Growth identities & temporal grammar</a><a href="/labs/engineering">State & control</a></div></section>
  <footer className="rce-footer"><p>Based on Heldt, Tyson, Cross & Novak’s published Chlamydomonas cell-cycle model. The numerical capsule retains its GPL licence and complete source.</p><a href="https://github.com/novakgroupoxford/2019_Heldt_et_al/tree/ab87e1314e27239d763e9cab188291e01b153574">Pinned upstream source</a><a href="/research-cases/Chlamydomonas_Observatory_Source.zip">Original complete source bundle</a><a href="/research-cases/chlamydomonas/FINDINGS.md">Findings & rejected leads</a><a href="/research-cases/chlamydomonas/upstream/LICENSE">GPL licence</a></footer>
 </main>;
}
