'use client';
/* oxlint-disable next/no-html-link-for-pages, next/no-img-element -- Stable native routes and original room photography. */
import {useState,useEffect,useRef,type CSSProperties} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,Eye,Map,Network,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SCIENCE_ROOMS,DEVICES,available,devicesForRoom,type ScienceRoom as Room,type Device} from '@/lib/observatory-catalogue';
import CentralDesk from './CentralDesk';

export function RoomDoors({compact=false}:{compact?:boolean}){return <div className={`science-doors ${compact?'doors-compact':''}`}>{SCIENCE_ROOMS.filter(r=>!r.mergedInto).map((r,i)=><a key={r.id} className="science-door" href={`/labs/${r.id}`} style={{'--room-accent':r.accent} as CSSProperties}><img src={r.image} alt={r.description} loading="lazy"/><span className="door-number">{String(i+1).padStart(2,'0')}</span><span className="door-plate"><small>{r.construction?'UNDER CONSTRUCTION':r.title}</small><strong>{r.name}</strong><span>{r.disciplines.slice(1,3).join(' · ')} <ArrowUpRight size={17}/></span></span></a>)}</div>;}
function frameUrl(href:string){const u=new URL(href,'https://observatory.invalid');u.searchParams.set('embedded','1');return u.pathname+u.search+u.hash;}
export default function ScienceRoom({room,initialDevice}:{room:Room;initialDevice?:string}){
 const [selected,setSelected]=useState<string|null>(initialDevice??null),[labels,setLabels]=useState(false),[inspect,setInspect]=useState(false),[arriving,setArriving]=useState(false);
 const [visited,setVisited]=useState<string[]>(initialDevice?[initialDevice]:[]);
 const frames=useRef<Record<string,HTMLIFrameElement|null>>({});
 useEffect(()=>{for(const [id,frame] of Object.entries(frames.current))frame?.contentWindow?.postMessage({type:'observatory/instrument-visibility',active:selected===id},location.origin);},[selected]);
 useEffect(()=>{const receive=(e:MessageEvent)=>{if(e.origin!==location.origin)return;const entry=Object.entries(frames.current).find(([,f])=>f?.contentWindow===e.source);if(!entry)return;if(e.data?.type==='observatory/return-to-room'){setSelected(null);setInspect(false);setArriving(false);}if(e.data?.type==='observatory/instrument-ready')frames.current[entry[0]]?.contentWindow?.postMessage({type:'observatory/instrument-visibility',active:selected===entry[0]},location.origin);};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[selected]);
 const members=devicesForRoom(room.id), device=DEVICES.find(d=>d.id===selected);
 function open(d:Device){if(d.id==='ida-headband'){window.location.assign('/ida');return;}setVisited(v=>v.includes(d.id)?v:[...v,d.id]);setInspect(false);setArriving(true);setSelected(d.id);}
 const close=()=>{setSelected(null);setInspect(false);setArriving(false);};
 return <main className={`science-room room-${room.id} ${labels?'show-object-labels':''} ${arriving?'at-instrument':''}`} style={{'--room-accent':room.accent} as CSSProperties}>
  <header className="room-topbar"><a href="/" aria-label="Return to the night office"><ArrowLeft size={17}/><span>Night office</span></a><div><span>{room.name}</span><h1>{room.title}</h1></div><button aria-label="Choose another science room" onClick={()=>setSelected('rooms')}><Map size={18}/><span>Other rooms</span></button></header>
  <section className="science-chamber" aria-label={`${room.title} interactive room`}><div className="chamber-pan"><div className="chamber-world"><img className="chamber-art" src={room.image} alt={room.description} fetchPriority="high"/><div className="chamber-shade" aria-hidden="true"/>{members.filter(m=>m.spatial).map(({device:d,placement:p},i)=><button key={d.id} className={`chamber-object ${available(d)?'':'object-planned'}`} style={{left:`${p.x}%`,top:`${p.y}%`,width:`${p.w}%`,height:`${p.h}%`}} aria-label={`${d.object}: ${d.label}${available(d)?'':' — under construction'}`} onClick={()=>open(d)}><span className="object-pin">{String(i+1).padStart(2,'0')}</span><span className="object-label"><small>{d.object}</small><strong>{d.label}</strong><em>{d.kind}</em></span></button>)}</div></div><div className="chamber-caption"><span>{room.construction?'THE NEXT ROOM IS TAKING SHAPE':'TOUCH AN INSTRUMENT TO BEGIN'}</span><p>{room.construction?'Under construction':room.disciplines.join(' · ')}</p></div><button className="chamber-label-switch" onClick={()=>setLabels(!labels)} aria-pressed={labels}><Eye size={17}/>{labels?'Hide labels':'Show instruments'}</button></section>
  <nav className="instrument-quickbar" aria-label={`${room.name} instruments`}><span>WITHIN REACH</span>{members.map(({device:d},i)=><button key={d.id} onClick={()=>open(d)}><small>{String(i+1).padStart(2,'0')}</small>{d.label}{!available(d)&&<em>planned</em>}</button>)}<button className="room-question" onClick={()=>{setVisited(v=>v.includes('question')?v:[...v,'question']);setSelected('question');setInspect(false);}}><Network size={17}/>Ask across the Observatory</button></nav>
  <Dialog open={selected!==null} onOpenChange={o=>{if(!o)close();}}><DialogContent keepMounted showCloseButton={false} className={`room-dialog station-${room.station} ${selected==='rooms'?'room-directory-dialog':''}`}><div className="room-dialog-heading"><div><DialogTitle>{selected==='rooms'?'Choose a room':selected==='question'?'The central inquiry network':device?.label}</DialogTitle><DialogDescription>{selected==='rooms'?'Different rooms. One connected Observatory.':selected==='question'?'Every question retains its assumptions, results and missing evidence.':device?.kind}</DialogDescription></div><div className="room-dialog-actions">{device&&<button aria-label="About this instrument and its connections" onClick={()=>setInspect(!inspect)} aria-pressed={inspect}><BookOpen size={17}/><span>About & connections</span></button>}<button onClick={close} aria-label={`Return to ${room.title}`}><X size={22}/></button></div></div>
    {selected==='rooms'?<div className="room-directory-scroll"><RoomDoors/><a className="catalogue-link" href="/catalogue">Inspect the Observatory catalogue <ArrowUpRight size={17}/></a></div>:<>
     {device&&(inspect||!available(device))&&<section className="instrument-notes"><p>{device.purpose}</p>{!available(device)&&<strong className="construction-seal">UNDER CONSTRUCTION</strong>}<div className="device-connections">{device.related.map(id=>{const r=DEVICES.find(d=>d.id===id)!;return <a key={id} href={`/devices/${id}`}>{r.label}<ArrowUpRight size={16}/></a>;})}</div><a href={`https://github.com/thantiklermcirony/empirical-observatory/blob/main/${device.source}`} target="_blank" rel="noreferrer">Inspect the source ↗</a><a href={`/devices/${device.id}`}>Permanent instrument link ↗</a></section>}
     {device?.id==='ida-headband'&&<div className="instrument-notes"><p>{device.purpose}</p><a className="ida-launch" href="/ida">Open the complete EEG laboratory ↗</a></div>}
    </>}
   {visited.map(id=>{const d=DEVICES.find(d=>d.id===id);if(id==='ida-headband')return null;return <div className="retained-instrument" hidden={selected!==id} key={id}>{(d?.branch||id==='question')?<div className="room-instrument-scroll"><CentralDesk initialBranch={d?.branch} active={selected===id} instrumentMode onRoomReturn={close}/></div>:d?.href?<iframe ref={node=>{frames.current[id]=node;}} onLoad={()=>frames.current[id]?.contentWindow?.postMessage({type:'observatory/instrument-visibility',active:selected===id},location.origin)} className="room-instrument-frame" title={d.label} src={frameUrl(d.href)} allow="fullscreen"/>:null}</div>;})}
   </DialogContent></Dialog>
 </main>;
}
