'use client';
/* oxlint-disable next/no-html-link-for-pages -- Stable native Observatory routes. */
import {useState} from 'react';
import LedgerReceipt from './LedgerReceipt';
import type {TemporalReport} from '@/lib/engine/temporal-router';
import {ObservatoryHeader} from './LaboratoryIdentity';
import type {scientificLedger} from '@/lib/scientific-ledger';
import {resolveScientificTerm} from '@/lib/scientific-vocabulary';
import './scientific-schematic.css';
type Ledger=ReturnType<typeof scientificLedger>;
export default function ScientificSchematic({ledger:l,initialRoom}:{ledger:Ledger;initialRoom:string}){
 const [stage,setStage]=useState(2),[room,setRoom]=useState(initialRoom),[term,setTerm]=useState('entropy'),[example,setExample]=useState('resource'),[missing,setMissing]=useState(false),[running,setRunning]=useState(false),[result,setResult]=useState<TemporalReport|null>(null),[error,setError]=useState('');
 const r=l.rooms.find(r=>r.id===room)!,devices=l.devices.filter(d=>d.room===room),terms=l.terms.filter(t=>t.rooms.includes(room)),resolved=resolveScientificTerm(term),s=l.stages[stage];
 async function run(){setRunning(true);setError('');setResult(null);try{const response=await fetch(`/api/ledger/run?example=${example}&removePremise=${missing?'1':'0'}`);const data:unknown=await response.json();if(!response.ok)throw Error('The declared example could not run.');setResult(data as TemporalReport);}catch(e){setError(e instanceof Error?e.message:'Execution failed.');}finally{setRunning(false);}}
 return <div className="scientific-map"><ObservatoryHeader/><main>
  <section className="sm-hero"><div><span className="sm-kicker">ENGINEERING DRAWING 001 / SHARED SCIENTIFIC LEDGER</span><h1>A map that can<br/><em>show its workings.</em></h1><p>Every room meets here. Follow a measurement into a named quantity, through a permitted operation, and back into evidence that can change what we know.</p><a href="#sm-engine" className="sm-primary">Trace the engine ↓</a> <a className="sm-primary" href="/ledger">Explore {l.ontology.totals.distinctIris.toLocaleString()} source identifiers ↗</a></div><aside className="sm-stamp"><span>OBSERVATORY / SYSTEM STATUS</span><strong>{l.coverage.fields.length}<small>science fields assigned a home</small></strong><div><b>{l.rooms.length}</b> rooms <b>{l.devices.length}</b> instruments</div><div><b>{l.terms.length}</b> seed concepts <b>{l.operations.length}</b> shared operations</div><p>Source vocabulary + execution contracts · Open coverage<br/>The map is broader than its working machinery.</p></aside></section>
  <section id="sm-engine" className="sm-engine"><div className="sm-section-label"><span>01 / THE ENGINE</span><span>SELECT A STAGE TO INSPECT</span></div><div className="sm-circuit">{l.stages.map((x,i)=><button key={x.id} onClick={()=>setStage(i)} aria-pressed={stage===i}><small>0{i+1}</small><strong>{x.title}</strong><span>{x.verb}</span></button>)}</div><div className="sm-return">↳ Evidence changes the model. The observation record stays traceable. ↰</div><div className="sm-stage"><div><span className="sm-kicker">{s.noun}</span><h2>{s.title}</h2></div><p>{s.detail}</p></div></section>
  <section className="sm-section" id="rooms"><div className="sm-section-label"><span>02 / THE SCIENTIFIC ATLAS</span><a href="/api/ledger">Read the machine ledger ↗</a></div><h2>Many rooms. Shared rules.</h2><p>Choose a room to see its instruments, scientific concepts and current execution coverage. A home on the map is a commitment to investigate; it is not a claim that the field has been solved.</p><div className="sm-room-tabs" role="group" aria-label="Science rooms">{l.rooms.map(x=><button key={x.id} aria-pressed={room===x.id} onClick={()=>setRoom(x.id)}>{x.name}{x.construction&&<small>BUILDING</small>}</button>)}</div><article className="sm-room-detail"><div><span className="sm-kicker">{r.title}</span><h3>{r.name}</h3><p>{r.description}</p><a className="sm-primary" href={`/labs/${r.id}`}>Enter this room ↗</a><p className="sm-fine">Fields {r.fieldIds.join(', ')||'Cross-disciplinary'}. All remain incomplete at the concept and model level.</p><p><a href={`/ledger?room=${r.id}`}>Browse this room’s imported scientific ledger ↗</a></p><h4>Scientific concepts</h4><div className="sm-tags">{terms.length?terms.map(t=><button key={t.id} onClick={()=>{setTerm(t.label);document.getElementById('language')?.scrollIntoView({behavior:'smooth'});}}>{t.label}</button>):<span>Detailed vocabulary is an explicit gap.</span>}</div></div><div>{devices.map(d=><div className="sm-device" key={d.id}><a href={`/devices/${d.id}`}>{d.label} ↗</a><p>{d.kind}</p><small>{d.governance}</small>{d.operationIds.map(id=><code key={id}>{id}</code>)}<a className="sm-code" href={`https://github.com/thantiklermcirony/empirical-observatory/blob/main/${d.source}`}>Source ↗</a></div>)}</div></article>
  <details className="sm-details"><summary>Inspect all {l.coverage.fields.length} fields and their homes</summary><p>Coverage scaffold adapted from <a href={l.coverage.source}>OECD Revised FOS 2007, Annex 1</a>. This taxonomy is a starting index, not a final partition of reality. Cross-disciplinary links can expand without duplicating instruments.</p><div className="sm-fields">{l.coverage.fields.map(f=><button key={f.id} onClick={()=>{setRoom(f.room);document.getElementById('rooms')?.scrollIntoView({behavior:'smooth'});}}><small>{f.id} / {f.room}</small><strong>{f.label}</strong><span>{f.scope}</span></button>)}</div></details></section>
  <section className="sm-section sm-split" id="language"><div><span className="sm-kicker">03 / LANGUAGE IS PART OF THE INSTRUMENT</span><h2>The word is the entrance.<br/>The definition is the key.</h2><p>Scientific nouns identify entities, quantities, states and models. Verbs describe possible operations. Only the narrower registered contracts below can authorise a calculation.</p><label htmlFor="term-resolve">Resolve a scientific term</label><input id="term-resolve" value={term} maxLength={120} onChange={e=>setTerm(e.target.value)} placeholder="Try entropy, state, ceiling, voltage…"/><div className="sm-tags">{['entropy','state','ceiling','voltage','nonsense'].map(x=><button key={x} onClick={()=>setTerm(x)}>{x}</button>)}</div><p className="sm-fine">Definitions are authored operational scopes. Reference links provide context; the seed vocabulary is not a certified ontology or a claim of exact equivalence to external vocabularies.</p></div><div className="sm-resolution" aria-live="polite"><span className="sm-kicker">{resolved.status.toUpperCase()} · NO CALCULATION AUTHORISED</span>{resolved.candidates.length?resolved.candidates.map(t=><article key={t.id}><h3>{t.label}</h3><p>{t.definition}</p><small>{t.kind} · {t.verbs.join(' · ')}</small><p className="sm-fine">{t.scope}</p><a href={t.source}>Reference context ↗</a></article>):<p>This label is not in the seed ledger. A proposed scientific concept needs a definition, source, scope and an ambiguity check before admission.</p>}</div></section>
  <section className="sm-section" id="contracts"><span className="sm-kicker">04 / FROM A VERB TO A CHECKABLE CALCULATION</span><h2>Permission lives in the premises.</h2><p>These contracts come directly from the same runtime used by the central structured inquiry engine. Change a required premise and the calculation must stop.</p><div className="sm-operations">{l.operations.map(op=><details key={op.id}><summary><strong>{op.verb}</strong><code>{op.id}</code></summary><p>{op.scope}</p><h4>Inputs</h4>{Object.entries(op.inputs).map(([key,v])=><p key={key}><code>{v.meaning}</code> · {key} · {v.units.join(' / ')} · {JSON.stringify(v.shape)}</p>)}<h4>Requires</h4><p>{op.premises.join(' · ')}</p><p>Output: {op.output.meaning} · {op.result_kind}</p></details>)}</div><div className="sm-run"><div><h3>Test the gate yourself</h3><label htmlFor="example">Declared model</label><select id="example" value={example} onChange={e=>{setExample(e.target.value);setResult(null);}}><option value="resource">Biology · necessary resource ceiling</option><option value="actions-ab">Mathematics · align then contract</option><option value="actions-ba">Mathematics · contract then align</option><option value="quantum">Physics · four-level quantum reference</option></select><label className="sm-checkbox"><input type="checkbox" checked={missing} onChange={e=>{setMissing(e.target.checked);setResult(null);}}/>Remove required premises</label><button className="sm-primary" disabled={running} onClick={run}>{running?'Checking & calculating…':'Run the registered example →'}</button><p className="sm-fine">Fixed illustrative inputs. No AI call, new measurement or automatic evidence admission. The receipt includes the actual calculation and contract checks.</p></div><div aria-live="polite">{error&&<p role="alert">{error}</p>}{result?<><LedgerReceipt report={result}/><button onClick={()=>{const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='observatory-ledger-receipt.json';a.click();URL.revokeObjectURL(url);}}>Download this receipt ↓</button></>:<div className="sm-empty">READY FOR A DECLARED QUESTION<br/><span>Inputs → premises → operation → result</span></div>}</div></div></section>
  <section className="sm-section"><span className="sm-kicker">05 / HOW THE LEDGER GROWS</span><h2>New evidence changes the map.</h2><div className="sm-growth">{l.growth.rules.map((rule,i)=><div key={rule}><small>0{i+1}</small><p>{rule}</p></div>)}</div><p>The present admission path is an editor-reviewed source revision. The <a href="/framework">framework proposal desk</a> can help prepare a claim and test; AI cannot mark its own proposal as an established law.</p><details className="sm-details"><summary>What is still unfinished?</summary><ul>{l.growth.gaps.map(g=><li key={g}>{g}</li>)}</ul><p>Next gate: migrate one measured instrument—including acquisition, uncertainty and observation identity—into the shared contracts. Use the paired-damage replay as a regression case and compare against its preserved baseline before admitting any new result.</p></details><p className="sm-fine">Architecture informed by <a href="https://jcgm.bipm.org/vim/en/2.3.html">VIM measurement definitions</a>, <a href="https://www.w3.org/TR/skos-reference/">SKOS concept labels</a>, <a href="https://www.w3.org/TR/prov-o/">PROV provenance</a> and <a href="https://obofoundry.org/principles/fp-006-textual-definitions.html">OBO scoped definitions</a>. Formal conformance to these standards is not claimed.</p></section>
 </main><footer>EMPIRICAL OBSERVATORY · Scientific ledger v1 <a href="/">Return to the night office ↗</a></footer></div>;
}
