'use client';
/* oxlint-disable next/no-html-link-for-pages -- Native routes preserve room navigation. */
import {useState} from 'react';
import {ArrowUpRight,FlaskConical,GitBranch,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {SCIENCE_CLAIMS,FRAMEWORK_SOURCES,CLAIM_LABELS,FRAMEWORK_REVISIONS,type ScienceClaim} from '@/lib/science-registry';
import {runFrameworkTest,type TestReceipt} from '@/lib/framework-tests';
import {DEVICES} from '@/lib/observatory-catalogue';
import FrameworkGrowth from './FrameworkGrowth';
import {ObservatoryHeader} from './LaboratoryIdentity';

export function ClaimCard({claim,onRun}:{claim:ScienceClaim;onRun?:(r:TestReceipt)=>void}) {return <article className="sf-claim" id={claim.id} data-class={claim.classification}><div className="sf-claim-top"><span>{CLAIM_LABELS[claim.classification]}</span><small>{claim.id} · r{claim.revision}</small></div><h3>{claim.title}</h3><p>{claim.statement}</p>{claim.equation&&<div className="sf-equation">{claim.equation}</div>}<dl><dt>Applies when</dt><dd>{claim.scope}</dd><dt>Why it is here</dt><dd>{claim.why}</dd><dt>Competing explanation</dt><dd>{claim.alternative}</dd></dl><details><summary>Sources and what is still needed</summary><ul>{claim.missing.map(m=><li key={m}>{m}</li>)}</ul>{claim.sourceIds.map(id=>{const s=FRAMEWORK_SOURCES.find(s=>s.id===id)!;return <a className="sf-source" key={id} href={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={14}/><small>{s.kind}</small></a>;})}</details><div className="sf-actions">{claim.testIds.map(id=><Button key={id} variant="outline" onClick={()=>onRun?.(runFrameworkTest(id))}><FlaskConical size={15}/>Run {id==='bounded-selector'?'law-selection challenge':'passive membrane check'}</Button>)}{claim.deviceIds.slice(0,2).map(id=>{const d=DEVICES.find(d=>d.id===id);return d?<a key={id} href={d.href??`/labs/${d.branch==='quantum'?'physics':d.branch}`} >{d.label}<ArrowUpRight size={14}/></a>:null;})}</div></article>}
export function FrameworkReceipt({receipt}:{receipt:TestReceipt}){const all=receipt.points.flatMap(p=>[p.baseline,p.candidate]),lo=Math.min(...all),hi=Math.max(...all),end=receipt.points.at(-1)!.x,start=receipt.points[0].x;const path=(key:'baseline'|'candidate')=>receipt.points.map(p=>`${30+(p.x-start)/(end-start)*640},${170-(p[key]-lo)/(hi-lo||1)*140}`).join(' ');return <section className="sf-receipt" aria-live="polite"><span className="sf-kicker">EXECUTED MODEL CHECK · {receipt.version}</span><h2>{receipt.outcome}</h2><p><b>{receipt.passed?'Declared check passed':'Declared check failed'}.</b> {receipt.passed?receipt.conclusion:'The declared check failed. Inspect the values and implementation before drawing the proposed conclusion.'}</p><svg viewBox="0 0 700 200" role="img" aria-label="Baseline and candidate calculation compared"><path d="M30 20V170H675" fill="none" stroke="#687b82"/><polyline points={path('baseline')} fill="none" stroke="#9be2c4" strokeWidth="3"/><polyline points={path('candidate')} fill="none" stroke="#e6b67a" strokeWidth="2" strokeDasharray="6 4"/></svg><p className="sf-legend">Green: {receipt.id==='bounded-selector'?'UHL':'analytic baseline'} · amber: {receipt.id==='bounded-selector'?'alternative bounded law':'numerical integration'}</p><dl className="sf-metrics">{Object.entries(receipt.metrics).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{Number(v.toPrecision(7))}</dd></div>)}</dl><p><b>Baseline:</b> {receipt.baseline}</p><p><b>Predeclared criterion:</b> {receipt.criterion}</p><details><summary>Inputs and limits</summary><pre>{JSON.stringify(receipt.inputs,null,2)}</pre><ul>{receipt.limits.map(l=><li key={l}>{l}</li>)}</ul></details><Button variant="outline" onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`${receipt.id}.json`;a.click();URL.revokeObjectURL(u);}}>Download execution record</Button></section>}
export default function ScienceFramework(){const [receipt,setReceipt]=useState<TestReceipt|null>(null);return <main className="science-framework"><ObservatoryHeader/><header className="sf-title"><span className="sf-kicker">PHYSICS / THE WORKING FRAMEWORK</span><h1>What holds.<br/><em>What might.</em></h1><p>Start with a known law. Make its assumptions visible. Test the next idea against it.</p><nav><a href="/labs/physics">Return to the Physics room</a><a href="/human">Open the living body<ArrowUpRight size={16}/></a><a href="/framework/work">Research workshop<GitBranch size={16}/></a></nav></header><Tabs defaultValue="known"><TabsList className="sf-tabs"><TabsTrigger value="known">Established & conditional</TabsTrigger><TabsTrigger value="hypotheses">Hypotheses & gaps</TabsTrigger><TabsTrigger value="history">Growth record</TabsTrigger></TabsList><TabsContent value="known"><div className="sf-grid">{SCIENCE_CLAIMS.filter(c=>c.branch==='physics'&&['established-reference','conditional-model'].includes(c.classification)).map(c=><ClaimCard key={c.id} claim={c} onRun={setReceipt}/>)}</div></TabsContent><TabsContent value="hypotheses"><div className="sf-grid">{SCIENCE_CLAIMS.filter(c=>['programme-hypothesis','open-question'].includes(c.classification)).map(c=><ClaimCard key={c.id} claim={c} onRun={setReceipt}/>)}</div></TabsContent><TabsContent value="history"><section className="sf-growth"><BookOpen/><h2>A history that can be corrected</h2>{FRAMEWORK_REVISIONS.map(r=><article key={r.id}><small>{r.date} · {r.id}</small><p>{r.description}</p><p>{r.evidence}</p></article>)}<p>New sources and AI investigations enter as proposed revisions. A test result keeps its scope; passing a simulation does not establish a physical law.</p><a href="/workbenches/learning">Watch an existing finite model family learn and retract predictions ↗</a></section><FrameworkGrowth/></TabsContent></Tabs>{receipt&&<FrameworkReceipt receipt={receipt}/>}</main>}
